### ISSUE TITLE
can we bind draggable event to the map and return update lat lng in function ?

### ISSUE THREAD

**Issue by jitchavan** [ErrorPro/react-google-autocomplete#1]
trying to use google autocomplete with react but need movable marker in the map. is it possible to modify this version with the requirement? any hint on it.

**Comment by ErrorPro** [comment]
@jitchavan I think it is. Let me check this out. Thank you.

**Comment by ErrorPro** [comment]
@jitchavan This plugin has no map. So what you can do. If you have a movable marker(or you can access to your map) you can get latitude and longitude in an object in onPlaceSelected function. Then you can use those locations to move(redraw) your marker. You just add new marker using those locations. Does it help you?
