### ISSUE TITLE
Error when running webpack -p command

### ISSUE THREAD

**Issue by remy-poirier** [ErrorPro/react-google-autocomplete#10]
I don't know if someone here has the solution to my problem but when I run `webpack-dev-server` everything works as expected but when I run `webpack -p` I don't see any errors but the component doesn't show up.

Here are some of my dependencies : 
`"react": "^15.4.1",`
`"react-dom": "^15.4.1",`
`"react-google-autocomplete": "^1.0.11",`
`"react-tap-event-plugin": "^2.0.1",`
`"material-ui": "^0.16.4"`

I tried a lot of thing but it's only when I remove `<Autocomplete
                    onPlaceSelected={(place) => {
                        console.log(place);
                    }}
                    types={['address']}
                    style={ inputStyle }
                />` that I can get a working code, and I have nothing logged to tell me where is the error...

Do you have any ideas ? Let me know if you need more informations

**Comment by ErrorPro** [comment]
@remy-poirier hm, really interesting behavior. -p option means production [shortcut](https://github.com/webpack/docs/wiki/cli#production-shortcut--p)  I'll check it soon and i get back to you once i find the problem and a solution. Thank you for your issue.

**Comment by remy-poirier** [comment]
Okay thank you and don't hesitate if you need more informations ! Really nice lib BTW !

**Comment by ErrorPro** [comment]
@remy-poirier Sorry for delay. I check it out. I works for me. With all your dependencies works. Have you solved the problem?

**Comment by ErrorPro** [comment]
Closing this issue since it's aging
