### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by HossamMarey** [ErrorPro/react-google-autocomplete#102]
just importing 'Autocomplete' to a page in a NextJs project give me this error 

> ReferenceError: Element is not defined
> ...node_modules/react-google-autocomplete/lib/index.js (173:71)

**Comment by ErrorPro** [comment]
@HossamMarey HI, I've just published v2.1.0 which has a fix for your issue. I tested it with nextjs and it worked
