### ISSUE TITLE
react-google-autocomplete not working in IE11

### ISSUE THREAD

**Issue by Samba-Shiva** [ErrorPro/react-google-autocomplete#103]
Good day,
I am using this react-google-autocomplete control in my SPFX React project. It is working fine in Chrome and Edge. However when I trying to access in IE11, its keep on loading but nothing happening. When I takeout this control from the form then its loading fine. Below are the some of the packages i am using. Can anyone assist on this.

"react-google-autocomplete": "^2.1.0",
"@types/react": "16.8.8",
 "@types/react-dom": "16.8.3",
"core-js": "^3.11.1",
"@pnp/polyfill-ie11": "^1.0.2",

**Comment by ErrorPro** [comment]
@Samba-Shiva Hey, thank you for your issue, working on it and will let you know when it's fixed

**Comment by ErrorPro** [comment]
Hi @Samba-Shiva, I just released the v2.1.2 where IE 11 should work. Shall you let me know if that does not fix the issue. Thanks
