### ISSUE TITLE
There is a way to specified `fields` using usePlacesAutocompleteService?

### ISSUE THREAD

**Issue by narcello** [ErrorPro/react-google-autocomplete#107]
I'm using usePlacesAutocompleteService and I wanna specified `fields` to return in predictions. Is it possible? Or even use the [getDetails](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.getDetails)

**Comment by ErrorPro** [comment]
For the `AutocompleteService` only [these](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest) options available, no fields option available. Regarding the `getDetails` service, to be able to call this method you need to have [different service](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService) to be available. I was going to add initiation of this service and bound it together with `usePlacesAutocompleteService`. If you could give me a bit more context about why you need to do this I could build this ASAP. @narcello

**Comment by ErrorPro** [comment]
@narcello closing this issue for now but I'd love to hear back from you @narcello

**Comment by adybuciuman** [comment]
I have the same problem. In my case, I need `getDetails` in order to fetch the coordinates. Besides city, region and country I need also latitude and longitutde and I see that `getPlacePredictions()` doesn't return the coordinates.

**Comment by ErrorPro** [comment]
@adybuciuman Hey! [`getDetails`](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.getDetails) is a different service(places-service) from google API. The mentioned hook only works with the [places-autocomplete-service](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service). I had an idea to initiate the places-service instance as well inside `usePlacesAutocompleteService` and return it so that anyone can use it. Let me know if that's something you' like to have to tell me more about how you would like to use it. Thanks!

**Comment by narcello** [comment]
@ErrorPro Thanks for answer me. 
My goal is get the cities and I want to get coordinates and formatted_address as well, to fill address form automatically with postal code, street, venue, etc.

**Comment by ErrorPro** [comment]
@narcello @adybuciuman hey guys! If the `usePlacesAutocompleteService` returns [`placesService`](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.getDetails) which you can call at any place in your component will that help you to solve your cases? for example

```
const { placePredictions, getPlacePredictions, placesService } =
    usePlacesService({
      apiKey: process.env.REACT_APP_GOOGLE,
    });

useEffect(() => {
  placesService. getDetails({ placeId: placePredictions[0].place_id, fields: ['geometry.location'] })
    .then(res => console.log(res))
}, [placePredictions]);
```  

or you can call this line when user selects a location from your autocomplete`onClick={() => placesService. getDetails({ placeId: el.place_id, fields: ['geometry.location'] })}`. In this case you can use an autocomplete session feature and only pay for a single session.

Let me know if there's any other way you'd prefer it to be. Thanks!

**Comment by thebiltheory** [comment]
> @narcello @adybuciuman hey guys! If the `usePlacesAutocompleteService` returns [`placesService`](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.getDetails) which you can call at any place in your component will that help you to solve your cases? for example
> 
> ```
> const { placePredictions, getPlacePredictions, placesService } =
>     usePlacesService({
>       apiKey: process.env.REACT_APP_GOOGLE,
>     });
> 
> useEffect(() => {
>   placesService. getDetails({ placeId: placePredictions[0].place_id, fields: ['geometry.location'] })
>     .then(res => console.log(res))
> }, [placePredictions]);
> ```
> 
> or you can call this line when user selects a location from your autocomplete`onClick={() => placesService. getDetails({ placeId: el.place_id, fields: ['geometry.location'] })}`. In this case you can use an autocomplete session feature and only pay for a single session.
> 
> Let me know if there's any other way you'd prefer it to be. Thanks!

Is this normal `usePlacesService` doesn't return `placesServices`?

Haven't found it either on the interface
```typescript
interface usePlacesAutocompleteServiceResponse {
  placesAutocompleteService: google.maps.places.AutocompleteService | null;
  placePredictions: google.maps.places.AutocompletePrediction[];
  isPlacePredictionsLoading: boolean;
  getPlacePredictions: (opt: google.maps.places.AutocompletionRequest) => void;
  queryPredictions: google.maps.places.QueryAutocompletePrediction[];
  isQueryPredictionsLoading: boolean;
  getQueryPredictions: (
    opt: google.maps.places.QueryAutocompletionRequest
  ) => void;
}

```

**Comment by thebiltheory** [comment]
How can we get the coordinates in the meantime?

**Comment by ErrorPro** [comment]
@thebiltheory @narcello I just added this functionality to the [lib](https://github.com/ErrorPro/react-google-autocomplete#returned-value-1).  You can use it as I described [here](https://github.com/ErrorPro/react-google-autocomplete/issues/107#issuecomment-849926788). Also there's a way to use a sessionToken to group requests.

**Comment by narcello** [comment]
@ErrorPro Nice, thanks. I just seen and I'll test it today. Thank you, I'll let you know about the tests :)

**Comment by narcello** [comment]
@ErrorPro Worked, but I had to pass a function callback to get the result from getDetails, little bit different from [here](https://github.com/ErrorPro/react-google-autocomplete/issues/107#issuecomment-849926788) but it's fine man, thanks again :)

**Comment by ErrorPro** [comment]
@narcello Yes it's a bit different cuz I supposed that the `getDetails` would return a promise but it [does not](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacesService.getDetails) :(
I will write a wrapper around its interface to `promisify` sometimes later. Hope the current implementation will work for a while :) Cheers!

**Comment by narcello** [comment]
@ErrorPro Don't worry, it's working :) thanks 🎉
