### ISSUE TITLE
Unable to set type against autocomplete

### ISSUE THREAD

**Issue by jdwholmes** [ErrorPro/react-google-autocomplete#108]
I'm using the autocomplete in my project alongside tailwindcss.

Tailwindcss by default applies styles to any input with [type]=*

The AutoComplete doesn't actually use type="text" by default, so these styles aren't applied.

I've tried adding type="text" to the autocomplete, which does work. But I get the following error:

Type '{ apiKey: string; className: string; onPlaceSelected: (place: any) => void; options: { types: string[]; componentRestrictions: { country: string; }; }; type: string; }' is not assignable to type 'IntrinsicAttributes & ReactGoogleAutocompleteInputProps'.
  Property 'type' does not exist on type 'IntrinsicAttributes & ReactGoogleAutocompleteInputProps'

**Comment by ErrorPro** [comment]
@jdwholmes Are you sure you're using the latest version of the lib? works for me on the latest version
![image](https://user-images.githubusercontent.com/6295152/118175241-24935f80-b430-11eb-85a2-e24091ae8e2c.png)
