### ISSUE TITLE
Propose to expose googleAutocompleteService from hook

### ISSUE THREAD

**Issue by WillXing** [ErrorPro/react-google-autocomplete#109]
Proposal to expose googleAutocompleteService from hook `usePlacesAutocompleteService`

**Current**

Only place predictions related function are exposed.

**Expect**

Have autocomplete service exported.

**Purpose**

To use service more flexible, user can operate function like get detail of place etc.

**Comment by ErrorPro** [comment]
Hey @WillXing , I just published v2.2.0 which exposes the instance, check [readme](https://github.com/ErrorPro/react-google-autocomplete#returned-value) section for more info
