### ISSUE TITLE
Styling not compatible with CSS modules

### ISSUE THREAD

**Issue by theredspoon** [ErrorPro/react-google-autocomplete#11]
When I try to style the component with Bootstrap (in accordance with best practices for globally-scoped CSS using CSS modules), nothing happens.

```<Autocomplete className="input-group" />``` renders the same as ```<Autocomplete />```

**Comment by ErrorPro** [comment]
@theredspoon Hello. Thank you for your issue. I will check it out asap.

**Comment by ErrorPro** [comment]
@theredspoon  http://jsbin.com/yogaculure/1/edit?html,css,js,output check this example out please.

**Comment by theredspoon** [comment]
I think the problem may be that the class 'input-group' needs to style a div. I'm not sure. Sorry I can't be more helpful.

**Comment by ErrorPro** [comment]
@theredspoon so it means that the problem isn't with this library. Perhaps changing your css will help.
