### ISSUE TITLE
Two Autocomplete Instances on Page

### ISSUE THREAD

**Issue by Smackface** [ErrorPro/react-google-autocomplete#112]
I can't seem to get more than one instance of the autocomplete to work per page. I am using the `const { ref } = usePlacesWidget({})` method. I have two separate consts, so that one is ref, and the other is newRef along with making sure the 2nd is as distinct from the first as possible. I currently have my two instances separated into two different React components called into the parent, here is my code for the two components: 

```  const [newPayload, setNewPayload] = useState();
  const [place, setPlace] = useState();
  const { newRef } = usePlacesWidget({
    id: "Origin",
    apiKey: process.env.REACT_APP_GOOGLE,
    onPlaceSelected: (place) => {
      const newPayload = {
        destination: {
          lng: place.lng,
          lat: place.lat,
          locationName: place.address_components,
        },
      };
      setPlace(place);
      setNewPayload(place);
      console.log(newPayload);
    },
    options: {
      componentRestrictions: { country: "us" },
      types: ["address"],
      fields: ["address_components", "geometry"],
    },
  });
  return (
    <div className={classes.InputGrid}>
      <TextField
        className={classes.InputText}
        variant="outlined"
        label="Origin"
        size="small"
        inputRef={newRef}
        name="Origin"
        id="Origin"
      />
    </div>
  );
}```

The other component is functionally the same, albeit with {ref}, (payload), id of "Destination" etc.

I apologize if this is formatted incorrectly or I left out important details, this is my first time opening an issue on GitHub as I am rather new to coding. Thank you for your time!

**Comment by ErrorPro** [comment]
@Smackface Hey! Thanks for your issue. The `usePlacesWidget` hook returns an object with [properties](https://github.com/ErrorPro/react-google-autocomplete#useplaceswidget). In the example I used destructuring to extract the ref, in your case you would also need to rename it for `const { ref: newRef } = usePlacesWidget({` so it will basically grab `ref` property from the returned value and assign it to the variable with the name `newRef`. Cheers!

**Comment by Smackface** [comment]
> 
> 
> @Smackface Hey! Thanks for your issue. The `usePlacesWidget` hook returns an object with [properties](https://github.com/ErrorPro/react-google-autocomplete#useplaceswidget). In the example I used destructuring to extract the ref, in your case you would also need to rename it for `const { ref: newRef } = usePlacesWidget({` so it will basically grab `ref` property from the returned value and assign it to the variable with the name `newRef`. Cheers!

This fixed it, unfortunately I'm struggling to get it working with Formik, I have been using the formik example you provided in the docs to try and figure it out. Thanks a ton for the response!
