### ISSUE TITLE
Handle Error Feature Request

### ISSUE THREAD

**Issue by ryanballa** [ErrorPro/react-google-autocomplete#116]
Hey, great library! Have you considered adding a prop for error handling for situations where wifi drops out or the user keeps the browser window open a long time and the session expires?

<img width="974" alt="Screen Shot 2021-06-21 at 9 27 32 AM" src="https://user-images.githubusercontent.com/728326/122779108-30661300-d273-11eb-8214-f207a5235b7f.png">

**Comment by ErrorPro** [comment]
@ryanballa Hey, thanks for the issue. No, I didn't consider such keys, unfortunately. Do you have time to create a PR? If not I will create this feature later this week.

**Comment by ErrorPro** [comment]
@ryanballa Could you please provide the whole stacktrace? It seems that it's an internal error thrown inside maps API library and we might not be able to intercept it but lets see your stack trace first.

**Comment by ErrorPro** [comment]
Close it due to staleness, if you have more info don't hesitate to reopen it
