### ISSUE TITLE
No dropdown when following examples

### ISSUE THREAD

**Issue by seanluse41** [ErrorPro/react-google-autocomplete#118]
Hello, really cool stuff here.
When I implement as following, the search box appears, but no dropdown appears. I believe there is no problem with Zindex.
Console does show return values of place.

Parent HTML:
```

      {/* 検索箱 */}
      <div style={{ position: "absolute", top: "50px", zIndex:"100" }}>
        <SearchBox/>
      </div>
```

Code from examples:
```
import { usePlacesWidget } from "react-google-autocomplete";

export default () => {
    const { ref } = usePlacesWidget({
      apiKey: "MY API KEY",
      onPlaceSelected: (place) => {
        console.log(place);
      },
      options: {
        types: ["address"],
        componentRestrictions: { country: "jp" },
        
      },
      language: "ja"
    });
    return <input ref={ref} style={{ width: "90%" }} defaultValue="東京" />;
  };
```

**Comment by ErrorPro** [comment]
@seanluse41 Hey! `usePlacesWidget` uses a default google Autocomplete widget which relies on some css properties. If you put it inside an absolutely positioned container the widget might not work as you expect. Try to wrap your component inside a relatively position container, might work
```<div style={{ position: "absolute", top: "50px", zIndex:"100" }}>
        <div style={{ position: "relative" }}>
           <SearchBox/>
         </div>
      </div>
```
