### ISSUE TITLE
Dropdown appears upside

### ISSUE THREAD

**Issue by adrienzagar** [ErrorPro/react-google-autocomplete#119]
Hey, I would like the dropdown appears upside the input. Is it possible to do this (maybe it's just a little css thing, I'm not sure) ?

**Comment by adrienzagar** [comment]
I found a solution changing the position of the div the contains autocompletion :
```
.pac-container {
  top: 625px !important;
}
```

The thing is that if completion contains only one or few addresses there is a gap between input and autocompletion like this : 
![Capture d’écran 2021-06-30 à 17 57 28](https://user-images.githubusercontent.com/59897360/123993516-c6651080-d9cc-11eb-804d-781a3b43858a.png)

Maybe someone have a better solution ?

**Comment by ErrorPro** [comment]
Hey @adrienzagar, unfortunately the Autocomplete widget provided by google is quite hard to customize. You might wanna use `usePlacesAutocompleteService` to fetch results yourself and put them in any order you'd like. P.S. You can try to use `flex: column-reverse` for the Autocomplete widget, not sure but it might work
