### ISSUE TITLE
Pass entire config object to the autocomplete?

### ISSUE THREAD

**Issue by chexxor** [ErrorPro/react-google-autocomplete#12]
Here: https://github.com/ErrorPro/react-google-autocomplete/blob/master/src/index.js#L19-L23

Instead of constructing this config object, can we pass it into the component through an attribute? The structure of this object is defined by Google, so this library only increases its maintenance burden by also knowing how to correctly create this config object. I imagine Google will be changing the options on this option in the future, so I want to avoid forcing us to make a new commit and new release of this library to support the new options.

If you think it's not a bad idea, I can make a PR.

**Comment by ErrorPro** [comment]
@chexxor Yeah this is a good idea. Though all users who use this library would have to change their code. I don't think that it is a good idea ;) What we can do is to add `const { types=['(cities)'], componentRestrictions={}, bounds,  ...rest} = this.props;` rest keys to the Autocomplete.

    new google.maps.places.Autocomplete(this.refs.input, {
      types,
      componentRestrictions,
      bounds,
      ...rest,
    });

It would be less pain for the others who use the library. What do you think?

**Comment by ErrorPro** [comment]
@chexxor Yeah this is a good idea. Though all users who use this library would have to change their code. I don't think that it is a good idea ;) What we can do is to add one more prop to the lib called `config` or smth like this. And just spread it into the Autocomplete config.

    const { types=['(cities)'], componentRestrictions={}, bounds, config} = this.props;

    this.autocomplete = new google.maps.places.Autocomplete(this.refs.input, {
      types,
      componentRestrictions,
      bounds,
      ....config,
    });

It would give us backward compatibility. What do you think?

**Comment by chexxor** [comment]
An idea I have:

```
    const { types=['(cities)'], componentRestrictions={}, bounds, config } = this.props;

    // !!! `types`, `componentRestrictions`, and `bounds` are deprecated.
    //     Delete these in a future major release and remove this if-statement.
    if (config) {
        this.autocomplete = new google.maps.places.Autocomplete(this.refs.input, config);
    else {
        this.autocomplete = new google.maps.places.Autocomplete(this.refs.input, {
          types,
          componentRestrictions,
          bounds,
        });
    }
```

**Comment by ErrorPro** [comment]
@chexxor Yeah actually spread operator replaces everything above it by keys and values in an object you provide. So let's do this:

    const { types=['(cities)'], componentRestrictions={}, bounds, config } = this.props;

    // !!! `types`, `componentRestrictions`, and `bounds` are deprecated.
    this.autocomplete = new google.maps.places.Autocomplete(this.refs.input, {
       types,
       componentRestrictions,
       bounds,
       ...config,
     });

Are you down with it?

**Comment by chexxor** [comment]
Yeah. I'll do that within the next week.
I wonder if you have a list of other breaking changes you're planning to make, as it would be nice to do a bunch of them at once. I'd make an issue for that if I were you, then keep adding to it until we'd like to make a major release, perhaps 6-12 months from now. I can make one

**Comment by ErrorPro** [comment]
Hm, it's a good idea! But i really have got nothing yet ;) But for sure i will create an issue with some future features and breaking changes. You are welcome to contribute and thank you!

**Comment by ErrorPro** [comment]
https://github.com/ErrorPro/react-google-autocomplete/issues/14

closing this issue.
