### ISSUE TITLE
usePlacesWidget with conditional rendering

### ISSUE THREAD

**Issue by ju2kr** [ErrorPro/react-google-autocomplete#122]
Hi all,
I'm struggling with a problem since a few days. 
I would like to use the usePlacesWidget hook with an input field, which is only rendered under certain conditions.
As soon as the field is not rendered it logically does not find the reference. If the field is rendered it finds the reference but the autocompletion does not work.

<img width="988" alt="Bildschirmfoto 2021-07-27 um 08 35 31" src="https://user-images.githubusercontent.com/8549484/127107383-1b8e8294-f207-408d-b945-9a3bb487a898.png">

When the input field is rendered on initial page rendering everything works as expected.

<img width="917" alt="Bildschirmfoto 2021-07-27 um 08 37 24" src="https://user-images.githubusercontent.com/8549484/127107404-3e6be0c2-fb68-4064-8608-d6aa0857738a.png">

**Comment by ErrorPro** [comment]
@ju2kr Hey! I think the easiest way to solve this is to hide inputs with css. Don't unmount them, just change `display:none|block`. If that's not possible for you then you can switch to use `<Autocomplete />` with `ref`. Store the ref inside the parent component and it'll work even if you unmount the `<Autocomplete ref={ref} />`
