### ISSUE TITLE
❗ By default the Autocomplete suggest regions as predictions! 

### ISSUE THREAD

**Issue by Farkadi06** [ErrorPro/react-google-autocomplete#123]
When instructing the Place Autocomplete service to return only business results I got no predictions. 
❗ The example :
```
import Autocomplete from "react-google-autocomplete";

<Autocomplete
        apiKey={API_Key}
        onPlaceSelected={(place) => console.log(place)}
        options={{
          types: ["(establishment)"]
        }}
     />
```

**Comment by AlexeyRDKV** [comment]
You must pass the types in quotes and everything will work.

```
options={{
      types: ["geocode", "establishment"]
   }}
```
Place types https://developers.google.com/maps/documentation/places/web-service/autocomplete#place_types
