### ISSUE TITLE
Only show place name instead of full address

### ISSUE THREAD

**Issue by ninjadev220** [ErrorPro/react-google-autocomplete#124]
I'd like to show place name instead of the full address in an inputbox.
However, when I select an address from the list of the places, it shows the full address firstly and then replaces the place name.
Isn't there a way to disable selecting the full address?

Here is a video record to show how it works.
http://cloud.movavi.com/show/f5iZzxlv48ydTe3bcVnNDtS6OEuBpIGW

`
<Autocomplete
  onPlaceSelected={(place, inputRef) => {
    inputRef.value = place.name
  }}
/>
`

**Comment by ErrorPro** [comment]
@ninjadev220 Hey, the autocomplete service has functionality out of the box which cannot be changed. The same applies to the value. What happens is you set the ref input value of the autocompelte service and then google overwrites it back. If you want to have custom behaviour/appearance u'd better try [places service](https://github.com/ErrorPro/react-google-autocomplete#useplacesautocompleteservice). That one can be customized as you wish
