### ISSUE TITLE
`options` does not allow `componentRestrictions` to be passed in when using Typescript

### ISSUE THREAD

**Issue by ClementineOldfield** [ErrorPro/react-google-autocomplete#126]
It looks like `options` in `usePlacesAutocompleteServiceConfig` is incorrectly typed as `QueryAutocompletionRequest` instead of `AutocompleteRequest`

https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service?hl=en#AutocompletionRequest

**Comment by ErrorPro** [comment]
@ClementineOldfield Thanks for your issue and PR!
