### ISSUE TITLE
Autocomplete list is scrolling away from the input.

### ISSUE THREAD

**Issue by kimberleykelly** [ErrorPro/react-google-autocomplete#131]
Issue: Autocomplete list is scrolling away from the input. I have tried lots of (not so nice hacks) to try and amend this. When I remove all of my own custom styling, the issue still persists.  

Please see attached screenshot from my project. 

<img width="302" alt="Screenshot 2021-09-15 at 14 26 00" src="https://user-images.githubusercontent.com/32412752/133441723-6587ba52-d56a-4236-ae9c-352411737c8a.png">

**Comment by ErrorPro** [comment]
@kimberleykelly Hey, it must be your local styles issue otherwise other people would have already reported(solved) it. What I would recommend is simply try to use the basic Autocomplete widget on not a styled page, see if it works without any additional styles from your side. Otherwise I would need a piece of code that I can run to test/debug it myself.

**Comment by R1cro** [comment]
Faced the same issue, @ErrorPro.

```  
const { ref } = usePlacesWidget({
    apiKey: GOOGLE_MAPS_API_CONFIG.apiKey,
    onPlaceSelected: (selected: any) => getPlaceDetails(selected),
    language: 'en',
    options: {
      types: ['address'],
      componentRestrictions: { country: 'us' },
      bounds: getAreaBounds(),
      strictBounds: false,
    },
  });
  
```

I added `ref` to simple `<input>` without any styles, also I turned off all global styles and use only one component with 'lorem ipsum; plain text (to add scroll on whole page and test it). 

Autocomplete block with search results is floating away from the input on any scroll.

**Comment by ErrorPro** [comment]
@R1cro Can u provide a jsbin or any other online js tools with a reproducible example?

**Comment by R1cro** [comment]
> @R1cro Can u provide a jsbin or any other online js tools with a reproducible example?

@ErrorPro, sorry, don't know how to setup react-google-autocomplete package in JSBIN or JSFiddle.  

But I can notice that is reproducible when current page with UI component able to scroll. You need just to add couple blocks of plain text before page scroll will appear, fill usePlacesWidget component input (your custom input with ref) and when dropdown with autocomplete results appear - make scroll.

Keep in mind that I turn all my styles (bootstrap and custom styles) and made the same test (not just on the mobile view - it reproducible also for desktop)  - still see floating dropdown :(

In my project it looks:
![chrome-capture-2022-5-21](https://user-images.githubusercontent.com/14110743/174789905-0ea5a0ff-1d22-4d24-99c8-6c3aa07631d2.gif)

Also my page structure:
<img width="460" alt="Screen Shot 2022-06-21 at 14 24 22" src="https://user-images.githubusercontent.com/14110743/174788333-315bb5d6-a33a-4606-be71-1e6831313e96.png">

Looks like the `.pac-container` render outside the form-control, appended in <body>.  Also it has (by default) `position: absolute !important` property. This normal behavior? 

Let me know if you need more details.

**Comment by R1cro** [comment]
Fast temp solution for this issue. I don't like this way, but this is temp solution.

We need to move `.pac-container` from `<body>` to form input section. So, we can use `appendChild()` to your `<div>` where exists your autocomplete input field.

```
useEffect(() => {
    // Google Autocomplete Widget Pop-Up/Dropdown Container
    const element = document.querySelector('.pac-container');

    if (element) {
      document.getElementById('address_autocomplete_section').appendChild(element);
    }
}, [addressField]); 
  ```
  
  Also apply this CSS code to your styles  like this one:
  
```
#address_autocomplete_section {
       position: relative !important;

       .pac-container {
            top: 80px !important;
            left: 0 !important;
        }
 }

```

CC: @ErrorPro need to find solution to place this component near input field instead of current behavior.
