### ISSUE TITLE
Debounce `usePlacesWidget`

### ISSUE THREAD

**Issue by pedrosimao** [ErrorPro/react-google-autocomplete#132]
Is there an easy way to have debounce in `usePlacesWidget` hook?
Or should I on a feature request? I could even code the feature if you think it's a nice idea...

**Comment by ErrorPro** [comment]
@pedrosimao Hey! Unfortunately, it is not possible to customize that hook as it has its own API underneath which handles outgoing requests and the input state. if you still wanna try to do that I'd love to see your outcome!
