### ISSUE TITLE
Keys exposed in HTTP Request

### ISSUE THREAD

**Issue by IvanDerlich** [ErrorPro/react-google-autocomplete#133]
When I make a request to google from the browser, the keys are exposed.
Anyone that gets access to those keys can start consuming the services and create charges on the key owner.
Is there a way to create a token that changes every request or every X seconds?
Or to encrypt the keys?

**Comment by ErrorPro** [comment]
@IvanDerlich Yes, I had the same questions back then. People indeed can use your API key as it's exposed. Google has a few tools to secure your API key, you can read about them [here](https://developers.google.com/maps/api-security-best-practices) if you still have any qs let us know
