### ISSUE TITLE
Missing `googleMapsScriptBaseUrl` in .d.ts file

### ISSUE THREAD

**Issue by yuval9313** [ErrorPro/react-google-autocomplete#134]
Hey,
I'm trying to use this lib but it is seems to be missing `googleMapsScriptBaseUrl` from typescript's `index.d.ts`

ATM I'm on node 14 and react-typescript with custom webpack config.
I've checked the parameters according to your docs and it does seems to work on `.js` and not on `.ts`.
I would appreciate you to look around

Thanks

**Comment by ErrorPro** [comment]
Hey @yuval9313, we just pushed a new version(2.4.3) where it's been fixed, thank you for the issue!
