### ISSUE TITLE
React Hook overrides the autocomplete attribute from Material UI TextInput

### ISSUE THREAD

**Issue by alacret** [ErrorPro/react-google-autocomplete#147]
When setting `autocomplete=off` on the TextInput from Material UI, and setting the `ref` it removes this attribute when rendered.

What we are trying to do is disable the chrome autocomplete box that shows on the HTML input

**Comment by alacret** [comment]
@wilme2

**Comment by ErrorPro** [comment]
@alacret I think theres a [prop](https://github.com/ErrorPro/react-google-autocomplete/issues/43) that you can use to overwrite that
