### ISSUE TITLE
Use the prop-types package

### ISSUE THREAD

**Issue by voold** [ErrorPro/react-google-autocomplete#15]
```Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead```

**Comment by ErrorPro** [comment]
Will do it asap.

**Comment by ErrorPro** [comment]
@voold fixed in .13 version. Please check it out.

**Comment by voold** [comment]
Thanks

2017-04-16 22:24 GMT+02:00 Ven Korolev <notifications@github.com>:
