### ISSUE TITLE
[Autocomplete] Render in parent instead of body?

### ISSUE THREAD

**Issue by plamenh** [ErrorPro/react-google-autocomplete#151]
Couldn't find a way to render the Autocomplete select in the parent element instead of body. We are having issue when using this in a Modal component, which treats any click outside of it as a close event. Am I missing something? Why does it have to render in body?

**Comment by ErrorPro** [comment]
You can always use `usePlacesWidget` hook and build it yourself

**Comment by SailingSteve** [comment]
I'm having a similar problem.  In a material-ui dialog, the GetPredictions calls are being sent to google and returning with good data, but the suggestions (Powered by Google) window is not appearing.  

I don't understand how the `usePlacesWidget` would solve the problem, could you explain or suggest an alternative approach for a fix?
