### ISSUE TITLE
AutoComplete - per session is not working even after setting sessionToken to true

### ISSUE THREAD

**Issue by mandula-abhilash** [ErrorPro/react-google-autocomplete#152]
Here is my code. Even after passing the `autocompleteSessionToken`, billing is generated per character instead of per session.

```
import React, { useState } from "react";
import useGoogle from "react-google-autocomplete/lib/usePlacesAutocompleteService";

const AutocompleteWidget = ({ setCenter, setZoom }) => {
  const {
    placePredictions,
    getPlacePredictions,
    isPlacePredictionsLoading,
    placesService,
    autocompleteSessionToken,
    refreshSessionToken,
  } = useGoogle({
    apiKey: process.env.REACT_APP_MAP_ACCESS_TOKEN,
    sessionToken: true,
  });
  const [value, setValue] = useState("");

  const getPlaceDetails = (placeId) => {
    placesService.getDetails(
      {
        placeId: placeId,
        fields: ["name", "formatted_address", "geometry"],
        sessionToken: autocompleteSessionToken,
      },
      (place, status) => {
        if (status === window.google.maps.places.PlacesServiceStatus.OK) {
          setCenter(place.geometry.location);
          setZoom(20);
        }
      }
    );
    refreshSessionToken();
  };

  return (
    <>
      <div className="fixed top-24 lg:top-6 z-10 w-full md:w-3/12 flex flex-col items-center justify-center">
        <input
          className="w-full p-2"
          value={value}
          onChange={(e) => {
            getPlacePredictions({
              input: e.target.value,
              sessionToken: autocompleteSessionToken,
              options: {
                componentRestrictions: { country: "uk" },
              },
            });
            setValue(e.target.value);
          }}
        />
        <div>
          {!isPlacePredictionsLoading &&
            placePredictions.map((prediction) => (
              <div onClick={() => getPlaceDetails(prediction.place_id)}>
                {prediction.description}
              </div>
            ))}
        </div>
      </div>
    </>
  );
};

export default AutocompleteWidget;

```

**Comment by ErrorPro** [comment]
Hey @mandula-abhilash Can you please check if `autocompleteSessionToken` changes between the renders? It should be the same per session. Let me know the result so I can try to help you

**Comment by AlexeyRDKV** [comment]
This issue was closed because it has been inactive for long time.

**Comment by FaisalMahamudCS** [comment]
Please reopen the issue .it is still there .i set session token true still session token not going
`const getPlaceDetails = (placeId) => {
        placesService?.getDetails(
            {
                placeId: placeId,
                fields: ["name", "formatted_address", "geometry"],
                sessionToken: sessionToken,
            },
            (place, status) => {
                if (status === window.google.maps.places.PlacesServiceStatus.OK) {
                   console.log(place);
                }
            }
        );
        const token = new window.google.maps.places.AutocompleteSessionToken();
        setSessionToken(token);
        refreshSessionToken();
    };
    console.log("session",sessionToken)`

    const {
        placePredictions,
        getPlacePredictions,
        isPlacePredictionsLoading,
        placesService,
        autocompleteSessionToken,
        refreshSessionToken,

    } = useGoogle({
        apiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY,
        sessionToken: true,

    });

    const [value, setValue] = useState("");
