### ISSUE TITLE
Want to get auto Complete when I switch countries

### ISSUE THREAD

**Issue by pointline** [ErrorPro/react-google-autocomplete#155]
Thanks a lot, great project

```javascript
<Autocomplete
  apiKey={YOUR_GOOGLE_MAPS_API_KEY}
  style={{ width: "90%" }}
  onPlaceSelected={(place) => {
    console.log(place);
  }}
  options={{
    types: ["(regions)"],
    componentRestrictions: { country: "us" },
  }}
  defaultValue="Amsterdam"
/>;
```
Modified country parameters
```javascript
<Autocomplete
  apiKey={YOUR_GOOGLE_MAPS_API_KEY}
  style={{ width: "90%" }}
  onPlaceSelected={(place) => {
    console.log(place);
  }}
  options={{
    types: ["(regions)"],
    componentRestrictions: { country: "gb" },
  }}
  defaultValue="Amsterdam"
/>;
```

Switch from us to gb, but the data obtained is still us

**Comment by menashkes** [comment]
Hey 

I'm also updating the options prop and the autocomplete is not responding to that. I believe there is a need to recreate the component registration to google but I'm not sure how.

Please advise

Thanks

**Comment by AlexeyRDKV** [comment]
Everything works, check if you accidentally use google api key with already set region in html.
`<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"
async defer></script>`
<img width="259" alt="Screenshot 2022-12-09 at 19 41 23" src="https://user-images.githubusercontent.com/43635842/206705169-f6cb1ef0-4229-483f-817a-52e66b9bf543.png">
<img width="259" alt="Screenshot 2022-12-09 at 19 42 04" src="https://user-images.githubusercontent.com/43635842/206705184-3ae02bd9-3dd3-4d0a-ad35-a88e6433c33b.png">
