### ISSUE TITLE
How to style Autocomplete box?

### ISSUE THREAD

**Issue by LefanTan** [ErrorPro/react-google-autocomplete#159]
Aside from getting the autocomplete box element using document.getElementByClassname, is there a better to style the box ('pac-container') as well as ('pac-item') ? It would be great if it is possible to get the element itself through autocompleteRef

![image](https://user-images.githubusercontent.com/12474777/161910864-19e0d9c0-9ad6-4862-aa35-9afa7cb4c71f.png)

**Comment by ErrorPro** [comment]
It's styled by google and you cannot change styles(at least easily)
