### ISSUE TITLE
How to filter restaurants rather than places ...

### ISSUE THREAD

**Issue by kamalkrishna3000** [ErrorPro/react-google-autocomplete#16]

**Comment by ErrorPro** [comment]
@kamalkrishna3000 All what you can use in this library is described here: https://developers.google.com/places/web-service/autocomplete

**Comment by kamalkrishna3000** [comment]
But I am unable to retrieve restaurants in Hyderabad or any particular location.

**Comment by ErrorPro** [comment]
Because it's a different library. I will try to implement this in the next version of this library but atm it is not possible. You are welcome to help me and do it yourself.
