### ISSUE TITLE
Force call onPlaceSelected with default value

### ISSUE THREAD

**Issue by wnieves** [ErrorPro/react-google-autocomplete#162]
Hi I'm using autocomplete component find some places in my app but I need get the place_id if I put a default address that I have in some prop, in this case which is the best way to achieve it? 

Thanks!

**Comment by ErrorPro** [comment]
The best way would be to use [usePlacesAutocompleteService](https://github.com/ErrorPro/react-google-autocomplete#useplacesautocompleteservice) and call its API `getPlacePredictions` then you can see if there's any result for such address and pick the one you need.
