### ISSUE TITLE
Handling error when api key is wrong

### ISSUE THREAD

**Issue by am2222** [ErrorPro/react-google-autocomplete#163]
Hi, 
When Api key is wrong I get an error that breaks my app. Is there any way to handel this error silently? I used an error boundary around the component but it still breaks my code.

**Comment by ErrorPro** [comment]
@am2222 The best way is to not render the input if apiKey is not provided. {apiKey ? <Autocompletet ... /> : null}

**Comment by adamwong246** [comment]
this doesn't really work for me

**Comment by am2222** [comment]
@adamwong246 I think a cleaner way is to develop an error boundary for this
