### ISSUE TITLE
Border Bottom Issue

### ISSUE THREAD

**Issue by CodeDruid13** [ErrorPro/react-google-autocomplete#164]
Found an issue, an underline shows on search and won't go away even on navigation to other screens

Default Search Input:  ![image](https://user-images.githubusercontent.com/19711569/172536436-b8333ec6-6d09-4adf-bc3f-49f2a29d462b.png)

After Search Input: ![image](https://user-images.githubusercontent.com/19711569/172537022-908016d6-e078-40e7-87c9-b8f52ed76354.png)

On Another screen: ![image](https://user-images.githubusercontent.com/19711569/172537588-59aa3146-229e-4a04-9da9-829d6538d66f.png)

This shows up even when using the Autocomplete. Is there any workaround this?

**Comment by ErrorPro** [comment]
Probably u are using some custom input. Check the source code of that input

**Comment by CodeDruid13** [comment]
Actually even when using the given input, it acts the same

**Comment by ErrorPro** [comment]
If it was an issue related to this library there would already be a few issues/answers. U can provide reproducible code and I can take a look
