### ISSUE TITLE
Autocomplete drop down is missing addresses

### ISSUE THREAD

**Issue by aar9nk** [ErrorPro/react-google-autocomplete#165]
Possibly a duplicate of [#117](https://github.com/ErrorPro/react-google-autocomplete/issues/117)

I'm currently using react-native-google-places-autocomplete in my React Native app and it displays far more address results. I am looking for street addresses so I have added that as a type. The bounds option is irrelevant and the rest is default.

**Comment by ErrorPro** [comment]
@aar9nk share the code so that I can run it to reproduce whats going on. But as u pointed out it could be that some properties not configured correctly
