### ISSUE TITLE
Not able to restrict the search suggestion to start after 3 characters.

### ISSUE THREAD

**Issue by santhoshspecbee** [ErrorPro/react-google-autocomplete#166]
Need to show suggestion after 3 characters. Currently shows suggestion after typing a single character.

![image](https://user-images.githubusercontent.com/80678500/176858748-f9345806-f7d5-4b07-bc37-a5eb5cb896b7.png)

- I am not able to find an atttrbute to provide minlength
- Also not able to find any event handlers to stop suggestion till some characters e.g: 3
- Please give some input to acheive this implementation

**Comment by santhoshspecbee** [comment]
@ErrorPro Please review.

**Comment by andaden** [comment]
@santhoshspecbee Could you please try using `debounce` prop?

**Comment by prabhakaran8737** [comment]
@andaden any example on how to use debounce, I use something like this but doesn't work

```
<Autocomplete
    debounce='1000'
    onPlaceSelected={(data) => {
        this.handlePlaceChange(data);
    }}
/>
```

**Comment by AlexeyRDKV** [comment]
You can use debounce with usePlacesAutocompleteService here is an example https://github.com/ErrorPro/react-google-autocomplete#useplacesautocompleteservice. 
`const {
    placesService,
    placePredictions,
    getPlacePredictions,
    isPlacePredictionsLoading
  } = usePlacesService({
    apiKey: process.env.REACT_APP_GOOGLE,
    debounce: 1500
  });`
You can leave a message [here](https://github.com/ErrorPro/react-google-autocomplete/issues/14) suggesting what you would like to add to ErrorPro/react-google-autocomplete
