### ISSUE TITLE
InvalidValueError: not an instance of HTMLInputElement

### ISSUE THREAD

**Issue by Hudhud** [ErrorPro/react-google-autocomplete#17]
I am developing an application, in Ionic, where you can plan a trip with a start address and an end address. However, I want to limit this feature to only one country. Before writing I have been searching for solutions on the internet, but none of them worked for me.

Have tried these suggestions:

https://stackoverflow.com/a/8282093/8130808

https://stackoverflow.com/a/10170421/8130808

Here is how I have tried to approach it:

I get the input from an alert dialog

    newRouteInput() {

    let alert = this.alertCtrl.create({
      title: 'New route',
      inputs: [
        {
          name: 'routeStart',
          placeholder: 'Start of route'
        },
        {
          name: 'routeEnd',
          placeholder: 'End of route'
        }
      ],
      buttons: [
        {
          text: 'Cancel',
          role: 'cancel',
          handler: data => {
            console.log('Cancel clicked');
          }
        },
        {
          text: 'Debug start and end',
          handler: data => {
            if (data.username !== "undefined") {
              console.log(data.routeStart + " " + data.routeEnd);
              this.routeStart = "Malmö";
              this.routeEnd = "Berlin";
              this.newRoutePlaceMarks(this.map);
              this.routeButton = false;

            } else {
              return false;
            }
            var input = document.getElementById(data.routeStart + " " + data.routeEnd);
            var autocomplete = new google.maps.places.Autocomplete(input);
            google.maps.event.addDomListener(input);
          }
        },
        {
          text: 'Place route markers',
          handler: data => {
            if (data.username !== "undefined") {
              this.routeStart = data.routeStart;
              this.routeEnd = data.routeEnd;
              this.newRoutePlaceMarks(this.map);
              this.routeButton = false;
            } else {
              console.log(data.routeStart + " " + data.routeEnd);
              return false;
              var input = document.getElementById(data.routeStart + " " + data.routeEnd);
            var autocomplete = new google.maps.places.Autocomplete(input);
            google.maps.event.addDomListener(input);
            }
          }
        }
      ]
    });
    alert.present();
     }

When I run this I get an error because of `data.routeStart + " " + data.routeEnd`.  What's the solution? :)

**Comment by ErrorPro** [comment]
@Hudhud How does it relate to this repo? :) Anyway I'll try to help you. Could you create an example in jsbin\jsfiddle?

**Comment by ErrorPro** [comment]
Try this
```
<Autocomplete
    style={{width: '90%'}}
    onPlaceSelected={(place) => {
      console.log(place);
    }}
    types={['(regions)']}
    componentRestrictions={{country: "ru"}}
/>```

And again, what is the title of this issue? Is that a problem?

**Comment by Hudhud** [comment]
It's implemented in typescript. I don't get the input from HTML but from an alert dialog that appears :)

**Comment by ErrorPro** [comment]
@Hudhud Anyway I don't really understand what's the problem and how to help you bro ;)

**Comment by Hudhud** [comment]
The problem is that it's not limited to only one country :) Anyway, thanks for trying :D
