### ISSUE TITLE
Longitude and Latitude

### ISSUE THREAD

**Issue by Veri5ied** [ErrorPro/react-google-autocomplete#171]
The location of longitude and latitude are not accessible. Make it accessible because we need to use it on some components. Now we need extra packages to convert the locations for us

**Comment by eliaharris** [comment]
You can. It's under `geometry.location` on the selected place.

```typescript
 onPlaceSelected={places => {
                            console.log(places.geometry.location.lat())
                            console.log(places.geometry.location.lng())
                        }}
```

**Comment by Veri5ied** [comment]
> You can. It's under `geometry.location` on the selected place.
> 
> ```ts
>  onPlaceSelected={places => {
>                             console.log(places.geometry.location.lat())
>                             console.log(places.geometry.location.lng())
>                         }}
> ```

Yeah I noticed it’s a function. Thank you

**Comment by Veri5ied** [comment]
Solved
