### ISSUE TITLE
Language setting is english but returns a different language

### ISSUE THREAD

**Issue by illlama** [ErrorPro/react-google-autocomplete#177]
Just like a bellow, search results aren't an English.

I tried to change language as korean or english or the others but the result is almost same ( I mean, US is change as I intended but `del Norte` part wasn't changed.)

![image](https://user-images.githubusercontent.com/13018853/185532772-f034aff0-954f-460f-bc8c-ef10f81c52b6.png)

And here's my code.
```
<StyledAutoComplete
                apiKey={process.env.GOOGLE_MAPS_API_KEY}
                onPlaceSelected={(place) =>...}
                options={{
                    types: ['administrative_area_level_1'],
                    componentRestrictions: { country: 'us' },
                }}
                language={'en'}
            />
```

I can't find a way to solve this problem I searched so I made an issue.

Thanks for this great library

**Comment by AlexeyRDKV** [comment]
The Google API uses the browser's preferred language setting when displaying textual information.
<img width="255" alt="Screenshot 2022-12-09 at 21 26 52" src="https://user-images.githubusercontent.com/43635842/206724290-9d98abfb-b942-4c08-b275-609e6ff36e9f.png">
<img width="259" alt="Screenshot 2022-12-09 at 21 27 36" src="https://user-images.githubusercontent.com/43635842/206724307-002bc769-fa9b-4d37-9fff-4f115b748c95.png">
<img width="697" alt="Screenshot 2022-12-09 at 21 29 20" src="https://user-images.githubusercontent.com/43635842/206724605-d7bf3df8-3a6f-4cb6-84d9-2a316ef7959d.png">

**Comment by lowfnm** [comment]
@AlexeyRDKV but how we can sort if we wanna only en or fr for example predictions?
