### ISSUE TITLE
Pac-container autosuggest not showing with mui dialog

### ISSUE THREAD

**Issue by e-reifer** [ErrorPro/react-google-autocomplete#184]
When using the autocomplete form with mui  in a dialog as suggested [here](https://github.com/ErrorPro/react-google-autocomplete/blob/master/docs/examples.js) the z-index values are not compatible with each other so that the autosuggest container will not be visible.

Mui Dialog (fullscreen) has a z-index of 1300 while the pac-container only has 1000. 

As a workaround I've decreased z-index of modal dialog but is there maybe a better way to directly affect the z-index of the pac container? 

Since my application has a vertical navigation and mobile burger menus which all would then be shown by the lower z-index of the modal, it'd be great to find a way to increase the z-index of the autocomplete container.

**Comment by AlexeyRDKV** [comment]
Hello, try set the z-index for the pac-container in the root css. 
`.pac-container {
  z-index: 100000 !important;
}`
<img width="343" alt="Screenshot 2022-12-09 at 13 20 14" src="https://user-images.githubusercontent.com/43635842/206638085-59b37398-f7ac-4d06-b768-aa26cdd14130.png">

**Comment by max-programming** [comment]
@AlexeyRDKV In my case, the autocomplete shows up but the mouse interaction doesn't work.
I am using ShadCN Dialog/Radix Dialog

**Comment by antonchuvirau** [comment]
> @AlexeyRDKV In my case, the autocomplete shows up but the mouse interaction doesn't work. I am using ShadCN Dialog/Radix Dialog

Have you found the solution?

**Comment by Gcarter17** [comment]
Ended up creating a Modal that's always mounted and gets visibility set to hidden when the typical dialog would be closed. Issue didn't seem to be with the z-index of the pac-container, but the way "materialRef" was getting handled with the mounting and unmounting of the dialog
