### ISSUE TITLE
Reset field ?

### ISSUE THREAD

**Issue by umair-khanzada** [ErrorPro/react-google-autocomplete#20]
I'm using this inside filters, Now I need to reset location to empty when clicked clear filter button, any idea.

**Comment by ErrorPro** [comment]
@umair-khanzada Hello, thank you for your questions, I will check it asap.

**Comment by ErrorPro** [comment]
@umair-khanzada it should look like this:

    <Autocomplete
          style={{width: '90%'}}
          onPlaceSelected={(place) => {
            console.log(place);
            this.setState({ value: place.formatted_address });
          }}
          onChange={(evt) => this.setState({ value: evt.target.value })}
          value={this.state.value}
          componentRestrictions={{country: "ru"}}
          types={[]}
        />
       <button onClick={() => this.setState({ value: '' })}>Reset</button>
