### ISSUE TITLE
Places API key restrictions

### ISSUE THREAD

**Issue by oliverbenns** [ErrorPro/react-google-autocomplete#219]
The places service hook actually requires both the `Places API` and `Maps Javascript API` to be enabled. I am not too familiar with the GCP API management but the latter was a surprise to me. This might be worth documenting somewhere.

**Comment by arthurakay** [comment]
YES thank you! I was looking for this specific documentation after wondering why I saw the errors.

**Comment by ErrorPro** [comment]
Added this to the docs, thanks @oliverbenns
