### ISSUE TITLE
Is it possible to automatically trigger the first selection of the autocomplete?

### ISSUE THREAD

**Issue by andresdicamillo** [ErrorPro/react-google-autocomplete#22]
Basically, when user types "New York" but you don't select exactly what the autocomplete returns, I need to select the first option.
I will really appreciate your help.

Thanks in advance!

**Comment by ErrorPro** [comment]
@andresdicamillo Hi, thank you for your issue. I will check it asap and get back to you with an answer.

**Comment by monarajhans** [comment]
+1

**Comment by monarajhans** [comment]
@ErrorPro Any updates on this? I am waiting on this as well.

**Comment by ErrorPro** [comment]
@andresdicamillo @monarajhans Autocomplete has only one [event](
https://developers.google.com/maps/documentation/javascript/reference#Autocomplete) unfortunately

But you always can do this(insert your api key in HTML tab): http://jsbin.com/luqupibaza/edit?html,js,output

The thing is we need to fire events on google api manually.

This is question on [stackoverflow](https://stackoverflow.com/questions/27865483/google-maps-api-autocomplete-search-without-selecting-from-dropdown)

**Comment by leonardoampuero** [comment]
Is it possible to get the prediction list? That might help for some cases.

**Comment by ErrorPro** [comment]
@leonardoampuero 
1. Use [queryprediction](https://developers.google.com/maps/documentation/javascript/examples/places-queryprediction)
2. Parse html down(select all predictions divs by classname) but I recommend you to use 1st way.

**Comment by ErrorPro** [comment]
Seems like everybody happy, you are always welcome.
