### ISSUE TITLE
Suggestions not coming in mobile android mozilla firefox untill you press space or symbols like "." 

### ISSUE THREAD

**Issue by vijayneophyte** [ErrorPro/react-google-autocomplete#24]
Suggestions not coming in mobile android mozilla firefox untill you press space or symbols like "."

**Comment by ErrorPro** [comment]
@vijayneophyte Thank you for your issue, I will check it as soon as possible and will let you know.

**Comment by ErrorPro** [comment]
@vijayneophyte Can you provide a bit more info, what version of mozilla are you using? I checked it and it worked for me.

**Comment by vijayneophyte** [comment]
Hi,

Thanks for the reply .
Its working in desktop but in Android mobile Mozilla Firefox it's not
working unless you press space or symbols
Device: Redmi note 5 pro(you can test in any other device also )
Firefox version: 59

Thanks
vijay

**Comment by ErrorPro** [comment]
Closing it due to ageing. If it reappears please let me know
