### ISSUE TITLE
Publish a new version

### ISSUE THREAD

**Issue by RickEyre** [ErrorPro/react-google-autocomplete#27]
Can you publish a new version?

I see that you removed the `<div>` [here](https://github.com/ErrorPro/react-google-autocomplete/blob/master/src/index.js#L47) that used to wrap the `<input>`. 

This update would be useful as the extra `div` is annoying as I have to take it into account when styling this component.

**Comment by ErrorPro** [comment]
@RickEyre Thank you for your issue. A new version of the lib has been published.

**Comment by RickEyre** [comment]
Thanks!
