### ISSUE TITLE
how to include multiple types on search.?

### ISSUE THREAD

**Issue by fr8in** [ErrorPro/react-google-autocomplete#28]
Hi,
   I am using react-google-autocomplete but when i search i need to get 

> (regions)
> establishment 

types can anyone tell me how to include more than one types in that component.?

**Comment by fr8in** [comment]
I searched and got that answer

**Comment by fr8in** [comment]
I searched and got that solution thank you

**Comment by 416serg** [comment]
@fr8in how did you solve it? right now if I do `types={['(regions)', 'address']}` the dropdown doesn't work. it works if I use one or the other

**Comment by owise1** [comment]
@416serg It looks like [you can't really use multiple types](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#AutocompletionRequest.types). I solved this my passing `false` in the `types` prop in order to return all the types.

**Comment by dmitriyaa** [comment]
@416serg, for me it doesn't work, I think it just falls back to cities.

**Comment by joeljerushan** [comment]
if anyone wonder how to get other types for example `establistment` try this 

```
import Autocomplete from 'react-google-autocomplete';
 
<Autocomplete
    style={{width: '90%'}}
    onPlaceSelected={(place) => {
      console.log(place);
    }}
    types={['establishment']} // like this 
    componentRestrictions={{country: "ru"}}
/>
```
