### ISSUE TITLE
Add address type to this component

### ISSUE THREAD

**Issue by mmatho** [ErrorPro/react-google-autocomplete#3]
Hello,
I am trying to use this autocomplete component. For now this is only suggesting cities as types = cities is hardcoded. Can this be extended for 'address' type?

**Comment by mmatho** [comment]
I created a branch to make this change to create a pull request for the below change. I can't push it to this origin as i am not a collaborator for this project,

   componentDidMount() {
     this.autocomplete = new google.maps.places.Autocomplete(this.refs.input, {
-      types: ['(cities)'],
+      types: ['(cities)', 'address'],
     });

**Comment by ErrorPro** [comment]
@mmatho I think it'd be better to allow users send types via props. Ok i will check this soon. Thank you.

**Comment by ErrorPro** [comment]
@mmatho I fixed the problem. Now you can pass whatever you want through types props. Please check [README.md](https://github.com/ErrorPro/react-google-autocomplete/blob/master/README.md)

**Comment by conor909** [comment]
So what is the recommended settings to find an exact address anywhere in the world?  I'm testing it out on my address but I can never find it, but I can find it on other demos on google.
