### ISSUE TITLE
"Can't find variable: google" error when rendering in mobile Safari and Firefox Focus

### ISSUE THREAD

**Issue by ImranNZ** [ErrorPro/react-google-autocomplete#35]
Environment: Tested on a iPhone 8 plus and also a Nexus 5.
Expected: Component Renders correctly
Actual: React application crashes on mobile as the google api cannot be found.

<img width="985" alt="screen shot 2018-08-13 at 7 50 02 pm" src="https://user-images.githubusercontent.com/3803838/44019195-3086fbd2-9f32-11e8-85c7-27784058d800.png">

**Comment by ImranNZ** [comment]
I should mention also that this is not a problem on desktop browsers, and on chrome on mobile.

**Comment by ErrorPro** [comment]
@ImranNZ Thanks for your issue, will check this

**Comment by NolanCrochot** [comment]
Exactly the same issue for me, but it occurs on all browsers (tested on Chrome / Firefox / Edge).

**Comment by serus22** [comment]
@mshahov do u use <script tag properly ? 
include google library dependency into <head>
or create wrapper which will wait until window.google.maps is available

**Comment by ErrorPro** [comment]
Closing this one cuz it's ageing. If this error occurs again, just create a new issue with more info how to reproduce it.
