### ISSUE TITLE
No `setFields` config option

### ISSUE THREAD

**Issue by ctowler157** [ErrorPro/react-google-autocomplete#36]
There is no clear exposed API for [setting the fields on the Autocomplete instance](https://developers.google.com/maps/documentation/javascript/reference/places-widget#Autocomplete.setFields). This is not ideal, as someone using this library might not realize _google includes all fields by default, charging you for the additional apis that those fields may involve_. To put it into context, someone who definitely isn't me used this in production and was charged $1400 for places API (expected) and an additional $700 for "atmosphere" and "contacts" data (unexpected)

For such an important configuration, there should be a first-class configuration option to handle this.

Currently, I have a ref on the input and am able to add my own config this way:
```
   componentDidMount() {
    this.inputRef.current.autocomplete.setFields(['formatted_address', etc.])
  }
```

**Comment by ErrorPro** [comment]
@ctowler157 Hey, thanks for the issue, really helpful. I will check this out asap, but if you have time to make a PR and submit it I would really appreciate that.

**Comment by ctowler157** [comment]
Won't get to this today, but I will do this Very Soon™

**Comment by ErrorPro** [comment]
@ctowler157 Thanks and looking forward to seeing your PR!

**Comment by mlucool** [comment]
@ctowler157 Were you ever able to add this?
