### ISSUE TITLE
Initialize input with a place

### ISSUE THREAD

**Issue by RickEyre** [ErrorPro/react-google-autocomplete#41]
Is there a way to initialize the input with a place? I set it to the full address text of the place right now, but it doesn't do a lookup onmount.

**Comment by WebbizAdmin** [comment]
Any luck on this?
I set value as an old comment says, but it then says on the edit form that this project is not authorised.

**Comment by ErrorPro** [comment]
Hey guys, it's just a plain html input, you can set value as you usually do: 'value={myValue}` it's the same as https://github.com/ErrorPro/react-google-autocomplete/issues/20, you can always put jsbin as a test example, so it would be much easier to help you right away.

**Comment by RickEyre** [comment]
I can set a text value yeah, but it doesn't fall on place selected initially. The user has to interact with the field to choose it still. Is there a way for the input to automatically load the place on intialization?

**Comment by ErrorPro** [comment]
Maybe you can try to call the google API internally but this library doesn't support that out of the box.

**Comment by ErrorPro** [comment]
@RickEyre If you find a solution please feel free to drop it here so I will tweak the lib to support it(or submit PR)!
