### ISSUE TITLE
Disable autofill does not work

### ISSUE THREAD

**Issue by RickEyre** [ErrorPro/react-google-autocomplete#43]
'disable-autofill' for `autocomplete` does not seem to work, but `off` does. Would you be open to switching it?

**Comment by ErrorPro** [comment]
@RickEyre Hi Rick, apologise for a late reply. I don't mind changing this prop to be coherent with google docs. Will you be able to submit a PR for that?

**Comment by lyquangthai1993** [comment]
attributes autocomplete from input default is disable-autofill make bug when web browser save old data input
like Chrome
![image](https://user-images.githubusercontent.com/21025255/69535126-c52c6000-0fad-11ea-94b7-28cdd8901f45.png)

pls change this.refs.input.autocomplete = 'disable-autofill'; to this.refs.input.autocomplete = 'off';

or make a variable attribute

thanks you

**Comment by ErrorPro** [comment]
I think there's a prop you can pass now to change autocomplete: `inputAutocompleteValue`
