### ISSUE TITLE
Styling autocomplete as per Material-UI design

### ISSUE THREAD

**Issue by kinsbrunner** [ErrorPro/react-google-autocomplete#44]
Hi, 
Has anyone been able to change the field styling as per material-ui styles? I have found the following [link](https://google-developers.appspot.com/maps/documentation/javascript/places-autocomplete#style_autocomplete) which explains all the relevant classes but it is being quite a mess to achieve it.
Any clues and answers would be very welcome!
Cheers.
Alejandro.

**Comment by ErrorPro** [comment]
@kinsbrunner Hi there, I think the best way would be for you to create your own component and use it. Alternatively, you can submit a PR which passes down a ref and renders nothing but null. So you can use any input just passing its ref down. It's a good issue though, will put it as a future improvement. Thanks.

**Comment by kinsbrunner** [comment]
Thanks for your answer. When could we expect to have this immprovement in place?

**Comment by ErrorPro** [comment]
@kinsbrunner Hey, I don't know when cuz I'm quite busy now. If you want you can help me with this. THanks.

**Comment by ErrorPro** [comment]
Closing this issue for now, if someone else is needed, please reopen.

**Comment by andrekutianski** [comment]
It would be interesting to be able to use any field to show the suggestions, this would allow you to use a field component of the MUI for example.
