### ISSUE TITLE
Get Latitute and Longitude

### ISSUE THREAD

**Issue by shehban** [ErrorPro/react-google-autocomplete#45]
Hello. I am using your autocomplete in my application and it's working very well, but I would like to know how I can get the Latitude and Longitude of the selected place. The data seems to be under geometry->location->lat->[[Scopes]][0] but I cannot access the data in [[Scopes]]. How would I get the latitude and longitude?

**Comment by ErrorPro** [comment]
You probably need to pass an appropriate field [prop](https://github.com/ErrorPro/react-google-autocomplete/blob/master/src/index.js#L10)
