### ISSUE TITLE
How to set bounds?

### ISSUE THREAD

**Issue by shehban** [ErrorPro/react-google-autocomplete#46]
Hey, I am using this module in my app but I am unable to set the bounds for a search. Do you have a written code example of bounds usage in this module?

**Comment by ErrorPro** [comment]
Hey @shehban, just pass it as a [prop](https://github.com/ErrorPro/react-google-autocomplete/blob/master/src/index.js#L9).

**Comment by joeljerushan** [comment]
@ErrorPro could yo please explain how it works ? check my code 
![image](https://user-images.githubusercontent.com/10111309/66364444-58321c00-e9a7-11e9-8ecb-eb4ea02fac18.png)
and i'm getting this error 
**`InvalidValueError: setBounds: not a LatLngBounds or LatLngBoundsLiteral: unknown property lat`**
![image](https://user-images.githubusercontent.com/10111309/66364464-6e3fdc80-e9a7-11e9-9acd-8735aaf1fa7a.png)

**Comment by BY-PacoLuna** [comment]
Did you solve it? @joeljerushan
