### ISSUE TITLE
How do i get the coordinates?

### ISSUE THREAD

**Issue by iamrenzx** [ErrorPro/react-google-autocomplete#49]
Hi is there anyway that i could get the value of the coordinates?

**Comment by ErrorPro** [comment]
@iamrenzx Can you provide more detail description? (possible with printscreens)

**Comment by iamrenzx** [comment]
Sorry i'm not on my pc right now but i'll try to explain. 

onSelectedPlace function can i return the coordinates of the place? Sometimes i only get an object with just the formatted address name. Sometimes i do get the an array of objects?

**Comment by iamrenzx** [comment]
<Autocomplete
    style={{width: '90%'}}
    onPlaceSelected={(place) => {
      //This parameter returns an object with only the name in it or an array of object i want it to consistently return an array of objects with the geometry, formatted address
      console.log(place);
     
    }}
    types={['(cities)']}
    componentRestrictions={{country: "ru"}}
/>

**Comment by ErrorPro** [comment]
@iamrenzx You need to [provide](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult) what additional data you want to receive. Google API isn't absolutely free, so by default the lib only gives you the minimum amount of data.
