### ISSUE TITLE
no action on pressing enter

### ISSUE THREAD

**Issue by Utsav170** [ErrorPro/react-google-autocomplete#52]
i want to know if on pressing enter is it possible to search the position. we have only onPlaceSelected funtion to work with.

**Comment by toddfichman** [comment]
I was wondering if this could be implemented as well

**Comment by ErrorPro** [comment]
Hi guys, you can pass any prop down to the lib and it will pass it through to the googleautocomplete input. So the answer is yes: just try it out.
