### ISSUE TITLE
placeholder text

### ISSUE THREAD

**Issue by ferdiozer** [ErrorPro/react-google-autocomplete#53]
how to change Autocomplete placeholder text ?
Thank you

**Comment by ErrorPro** [comment]
@ferdiozer it's a standard html input under the hood. Any props you pass will be passed down to that standard html. So just try `placeholer="My"`

**Comment by ferdiozer** [comment]
> @ferdiozer it's a standard html input under the hood. Any props you pass will be passed down to that standard html. So just try `placeholer="My"`
![image](https://user-images.githubusercontent.com/18518803/63022157-f1165080-beaa-11e9-83dc-2c16ac9722aa.png)

not working. I use react js
