### ISSUE TITLE
API is giving limit exeed

### ISSUE THREAD

**Issue by kratika-lahoti** [ErrorPro/react-google-autocomplete#54]
i am getting below error.

"You have exceeded your daily request quota for this API. If you did not set a custom daily request quota, verify your project has an active billing account: http://g.co/dev/maps-no-account  For more information on usage limits and the Google Maps JavaScript API services please see: https://developers.google.com/maps/documentation/javascript/usage"

i want autocomplete call api after 3 char or 5 char currently it get hit on first char,

**Comment by kratika-lahoti** [comment]
According to https://developers.google.com/maps/premium/previous-licenses/articles/usage-limits

Upon receiving a response with status code OVER_QUERY_LIMIT, your application should determine which usage limit has been exceeded. This can be done by pausing for 2 seconds and resending the same request. If status code is still OVER_QUERY_LIMIT, your application is sending too many requests per day. Otherwise, your application is sending too many requests per second.

**Comment by ErrorPro** [comment]
This is not related to this library. You need to check how many times you've used your API key

**Comment by kratika-lahoti** [comment]
> This is not related to this library. You need to check how many times you've used your API key

i know that, what i want is to call api after user type 3 char or 5 char, currently it get hit on first char
