### ISSUE TITLE
 Cannot read property 'remove' of null (on unmount)

### ISSUE THREAD

**Issue by nicholeuf** [ErrorPro/react-google-autocomplete#57]
Officially putting in an issue for documentation purposes.  Please accept our PR as a fix https://github.com/ErrorPro/react-google-autocomplete/pull/56.  Thank you!  

We are seeing a sporadic issue in production and have narrowed down the source to this line from our Honeybadger reports.  Hopefully this will help others as well.  

Honeybadger backtrace: 
![image](https://user-images.githubusercontent.com/16197461/63651896-e324c300-c727-11e9-890d-a0db5407b890.png)

**Comment by ErrorPro** [comment]
Merged
