### ISSUE TITLE
null is not an object (evaluating 'this.event.remove')

### ISSUE THREAD

**Issue by nicholeuf** [ErrorPro/react-google-autocomplete#58]
👋 We are seeing 359 occurrences in production with the error: `null is not an object (evaluating 'this.event.remove')`.  We were using version 1.1.0 of this library and will be upgrading to latest as soon as possible.

I am submitting a PR shortly to defensively check for the existence of this.autocomplete.  

![image](https://user-images.githubusercontent.com/16197461/63652156-27659280-c72b-11e9-865c-6850c26fea42.png)

**Comment by ErrorPro** [comment]
@nicholeuf Thank you for your PRs.
