### ISSUE TITLE
Unknown Prop Warnings after upgrade to react@15.3.1

### ISSUE THREAD

**Issue by 7lion** [ErrorPro/react-google-autocomplete#6]
After upgrade from react@15.1 to react@15.3.1 I started to get warnings like:
warning.js?8a56:44Warning: Unknown prop `onPlaceSelected` on on <input> tag. Remove this prop from the element.

**Comment by elanperach** [comment]
+1

**Comment by ErrorPro** [comment]
Thanks guys. I will fix it soon.

**Comment by ErrorPro** [comment]
Fixed in 1.0.6.
