### ISSUE TITLE
Establishment Support

### ISSUE THREAD

**Issue by joeljerushan** [ErrorPro/react-google-autocomplete#61]
is it possible to get input text of Establishment ? my code 

```
<Autocomplete
    style={{width: '100%'}}
    placeholder="Input Establishment Name"
    onPlaceSelected={(place) => {
        console.log(place)
    }}
    types={['establishment',]}
    componentRestrictions={{country: "lk"}}
    name="place_name"
    value={this.state.place_name}
    onChange={this.handleInputChange}
/>
```
![image](https://user-images.githubusercontent.com/10111309/66305912-042f2500-e91e-11e9-97aa-26467ee03a03.png)

Input name not there :( only returning this 
![image](https://user-images.githubusercontent.com/10111309/66305952-1b6e1280-e91e-11e9-884b-847414902f00.png)
help needed

**Comment by Jpetchan** [comment]
you can use like this.

onPlaceSelected={(place, input) => {
        // console.log(place)
        console.log(input.value)
    }}

i hope this useful for you.

**Comment by goleary** [comment]
you should just pass the desired fields to the Component:

```
<Autocomplete
    style={{width: '100%'}}
    placeholder="Input Establishment Name"
    onPlaceSelected={(place) => {
        console.log(place)
    }}
    types={['establishment',]}
    componentRestrictions={{country: "lk"}}
    name="place_name"
    value={this.state.place_name}
    onChange={this.handleInputChange}
    fields=["formatted_address", "place_id", "name"]
/>
```

`name` is the one you are looking for.

![image](https://user-images.githubusercontent.com/16123225/68342501-98b4b080-009f-11ea-936d-dac0a7b2f111.png)

**Comment by ErrorPro** [comment]
Previous comments answer the original question I believe. Closing it.
