### ISSUE TITLE
Any possibility to manually change the value ? 

### ISSUE THREAD

**Issue by yamakhalah** [ErrorPro/react-google-autocomplete#62]
Hi,

I would know if there is a possibility to manually change the value which is shown in the textfield ? Or to bind it.

I work with the map and for some reason i would let people to choice between search for an adresse through your autocomplete component or by clicking on the map.

Best regard

**Comment by dyaacov** [comment]
.

**Comment by ErrorPro** [comment]
@yamakhalah you can always pass any value you want to the underlying html element
