### ISSUE TITLE
How to add address to on top of (regions) in types?

### ISSUE THREAD

**Issue by MariuzM** [ErrorPro/react-google-autocomplete#64]
I want to search using Cities and Address, from my understanding to search address i need to use  `types={['address']}` and for regions `types={['(regions)']}`, how can i include both of them?

I have tried `types={['(regions)', 'address']}` but not working :(

**Comment by groovychoons** [comment]
Hi @MariuzM 
Google Places doesn't currently support multiple types, but using type geocode should solve this:

`          <Autocomplete

            onPlaceSelected={this.props.onPlaceSelected}
            types={["geocode"]}
          />`
