### ISSUE TITLE
How to add bias - location and radius

### ISSUE THREAD

**Issue by sseppo** [ErrorPro/react-google-autocomplete#66]
To use Location biasing rather than restriction, one should include location and radius in the call to google. How to use them in your component? I tried just to add them as props like this:
location='10,123356, 24,364364'
radius='10000'

but they did not work. Is it possible with current version, and if not, could it be added?

**Comment by sebastianpinosanchez** [comment]
Hi, I'm trying to add the location and radius using `componentRestrictions` prop but it doesn't work for me. Have you found any solution for the current version `(1.1.2)` ?. Regards

**Comment by wynxnyw** [comment]
This is something I am very interested in as well. This will fulfill most peoples complete needs!

**Comment by ronenmagid** [comment]
Try this:

` geolocate = () => {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var geolocation = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };
                var circle = new google.maps.Circle(
                    {center: geolocation, radius: position.coords.accuracy});
                autocomplete.setBounds(circle.getBounds());
            });
        }
    }`

Call this function on the "onFocus" on the search bar or when you mount the component.

**Comment by ErrorPro** [comment]
Just pushed a new version with #76 merged in it. Might be something you are looking for. If it's not then you are welcome to submit a PR.
