### ISSUE TITLE
Getting error: google is not defined

### ISSUE THREAD

**Issue by Closery** [ErrorPro/react-google-autocomplete#67]
Hi,
I'm using NextJS and I import the component;
`import Autocomplete from 'react-google-autocomplete';`

And I use it like this;
`<Autocomplete
								type="text"
								onPlaceSelected={(value) => this.setState({ myValue: value.formatted_address })}
							/>`

But I'm getting an error: 
`index.js:66 Uncaught ReferenceError: google is not defined`

I have two pages which I want to use the Autocomplate component, in one of them when I refresh the page (normally I use next Link component to route between pages), google is not defined error disappear and the page works.
On the other page I'm getting same error and refreshing the page is not work on this page but interestingly when I go my first page and refresh then route to my second page, everything works. So I can't directly go to my second page :/

**Comment by Closery** [comment]
Edit: Ah sorry, its totally my fault. I forget to include the google api address on my second page like this:
`<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=[API_KEY]&libraries=places">`

**Comment by Pardeep94** [comment]
I get this error even after defining the script in my html file

**Comment by wisdomtooth546** [comment]
For someone encountering this in nextjs. Use `Script` from nextjs and add it into your component.
```
<Script
        async
        type="text/javascript"
        src={`https://maps.googleapis.com/maps/api/js?key=GOOGLE_MAPS_API&libraries=places&loading=async`}
      ></Script>
```
