### ISSUE TITLE
i want to get full address like street number and street address also

### ISSUE THREAD

**Issue by tamjidtech** [ErrorPro/react-google-autocomplete#68]
right now i only get city, state and country. and while i type an address with street number nothing comes up on suggestion only when i type city it's comes up with city, state, country. but i try with type regions but it's still same not getting full address.

**Comment by groovychoons** [comment]
If you set types to "address" or "geocode", this should solve your problem.
`          <Autocomplete
            onPlaceSelected={this.props.onPlaceSelected}
            types={["geocode"]}
          />
`

**Comment by ErrorPro** [comment]
Thanks to @groovychoons closing the issue.
