### ISSUE TITLE
Consider to use all optional parameters

### ISSUE THREAD

**Issue by mathvaleriano** [ErrorPro/react-google-autocomplete#72]
Hi, thank you for this project.
I think you could use all optional parameters in the request, because, for example, I need to consider the origin to get relevant items in the response.
What do you think about it?

**Comment by ErrorPro** [comment]
I think it makes sense and might be a good feature. Can you please participate in this matter? I'd rather have an additional prop to not change the behavior of existing logic as some people already relied on it. @mathvaleriano what do you think?

**Comment by mathvaleriano** [comment]
Sure 😄 . We dont want breaking changes. 
Can I make a pull request?
