### ISSUE TITLE
Retrieving Autocomplete Predictions

### ISSUE THREAD

**Issue by pvernekar-cci** [ErrorPro/react-google-autocomplete#73]
I want to retrieve autocomplete predictions before selection.

**Comment by ErrorPro** [comment]
I think at this moment it's not possible. But you have a few options:
1. Get whatever you get in onPlaceSelected and do not change the value of the underlying input unless you need it.
2. Submit a PR which adds additional prop onPlacePredictions or smth like that and implement it in a PR.

Cheers.

**Comment by pvernekar-cci** [comment]
So, you mean to say... If I want to append something to the autocomplete dropdown that is not possible right now correct?
