### ISSUE TITLE
 Getting error: google is not defined

### ISSUE THREAD

**Issue by Pardeep94** [ErrorPro/react-google-autocomplete#75]
I get the following error.

I used `react-google-autocomplete` in my 2 component.

It is working fine in one component but I am getting this error in my second component.

I even define the google script in html file.

![Screenshot from 2020-04-28 16-37-47](https://user-images.githubusercontent.com/18335284/80480654-abcd7c80-896e-11ea-8404-307c61171d38.png)

**Comment by rherugu** [comment]
Do you have the code: 
`<script
      type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=[YOUR_API_KEY]&libraries=places"
    ></script>`

in the index.html file?

If you don't, replace YOUR_API_KEY with the google API key.

**Comment by Pardeep94** [comment]
I already add this in my html file. That's why it is working in my one component. When I am using it in another component it gives me this error

**Comment by Aravindhsiva** [comment]
Yeas, got this same error. Any solutions??🤔🤔

**Comment by Pardeep94** [comment]
I solved this issue .

I add the script below to the body and I am getting above error.

after adding the script above body in my html file. this issue solved
