### ISSUE TITLE
Updating bounds does not update the records.

### ISSUE THREAD

**Issue by pvernekar-cci** [ErrorPro/react-google-autocomplete#77]
I have a scenario of Pickup and Dropoff location.

Initially, I set the bounds. If the user searches for any other Pickup location, bound values are updated in the console but `Autocomplete` doesn't reflect any changes with the updated bounds in the Dropoff dropdown.

![Screenshot 2020-05-05 at 5 24 42 PM](https://user-images.githubusercontent.com/16555687/81063440-66bcc380-8ef5-11ea-9e3e-17b8788f16f2.png)

@ErrorPro Any help on this.

**Comment by deekshugupta** [comment]
I am also facing the same

**Comment by pvernekar-cci** [comment]
@ErrorPro any update?

**Comment by ErrorPro** [comment]
It won't reflect as its being built on component did mount and when you change it's props the autocomplete doesn't get rebuilt. The easiest way to get what you need is to pass a unique key to autocomplete every time you google autocomplete to reflect your changes. Another solution would be to implement `componentDidUpdate` and check whether config props have been changed and if so then just reinitialize the autocomplete. Let me know if this solves your issue.
