### ISSUE TITLE
Adding Default address Text not working

### ISSUE THREAD

**Issue by zelin** [ErrorPro/react-google-autocomplete#78]
I am using v1.2.4 and using code

`<Autocomplete   
							googlemap={this.state.googleMapProps.googlemap}
							style={{
								marginLeft: 15, marginRight: 15,
								backgroundColor: "green",
								outline:"none",
								fontSize: 16, fontFamily: "main-regular",
								backgroundColor: '#F5F5F5', 
								height: 40, 
								flex:1,
								border:'none',
								borderRadius: 10,
								paddingLeft: 15,
								paddingTop: 10,
								paddingBottom: 10
							}}
							inputAutocompleteValue={this.state.location.address}
							onPlaceSelected={this.onPlaceSelected}
							types={['(regions)']}
							//componentRestrictions={{country: store.countries}}
						/>)}
`

It seems that inputAutocompleteValue is not adding default address to the input. How will I make it work.

**Comment by ronenmagid** [comment]
` defaultValue={"new York"}`
