### ISSUE TITLE
InvalidValueError: not an instance of HTMLInputElement

### ISSUE THREAD

**Issue by richraid21** [ErrorPro/react-google-autocomplete#8]
When using the default example, this error is returned in the console.

**Comment by ErrorPro** [comment]
@richraid21 Thank you for your issue. I will check it soon.

**Comment by ErrorPro** [comment]
@richraid21 Can you give me an example? Or could you tell me your react's version? I dont see any error on my test example.

**Comment by ErrorPro** [comment]
I am closing this issue cuz it's probably out of date.

**Comment by balubunny4u** [comment]
I am facing same issue.Kindly help me.
![screen shot 2017-03-16 at 7 41 45 pm](https://cloud.githubusercontent.com/assets/15211745/24000226/aaa30b24-0a80-11e7-95cc-e63e2b8c3323.png)

**Comment by ErrorPro** [comment]
@balubunny4u Are you sure this problem is related to Autocomplete? Can you expand the stack trace and show me?

**Comment by balubunny4u** [comment]
I have used autocomplete in multiple pages.That's why i got same error multiple times.
![screen shot 2017-03-16 at 7 48 57 pm](https://cloud.githubusercontent.com/assets/15211745/24000587/a3a98c0c-0a81-11e7-9176-4c55bb5fb4e0.png)

**Comment by ErrorPro** [comment]
@Bunny2242 Ok thank, i'll check it asap and let you know.

**Comment by Kambe11** [comment]
.pac-container {
    z-index: 1051 !important;
}

**Comment by ErrorPro** [comment]
@Kambe11 what's that?

**Comment by eduardichim** [comment]
@ErrorPro I think I've found the problem.

I've used your strategy to pick up the element through ref and in version
├── react@16.4.1
└── react-dom@16.4.1
in order to get have the same effect as document.getElementById('pac-input') i do this.ref.current

`
    constructor(props) {
        super(props);

        this.autocomplete = null;
        this.event = null;
        this.input = React.createRef();

        this.onSelected = this.onSelected.bind(this)
    }

    componentDidMount() {
        this.autocomplete = new google.maps.places.Autocomplete(this.input.current);
        this.event = this.autocomplete.addListener('place_changed', this.onSelected);
    }

    componentWillUnmount() {
        this.event.remove();
    }

    onSelected() {
        console.log(this.autocomplete.getPlace());
    }

    render() {
        return (
            <div>
                <input type="text" ref={this.input}/>
            </div>
        );
    }
`

**Comment by ErrorPro** [comment]
@eduardichim Sorry, I've just seen your message, will give it a try later today. Thanks for the info!

**Comment by ErrorPro** [comment]
@eduardichim http://jsbin.com/tahijugolo/edit?js,output

Does anyone still have this problem?

I can update this lib to use React.createRef(), but it'll affect people who are using the lib already to update theirs react package to 16.3 at least, to support React.createRef.

**Comment by MattSidor** [comment]
@ErrorPro I think this change should have been a 1.1.x release instead of 1.0.x.

**Comment by ErrorPro** [comment]
@MattSidor I agree, I'll do it asap but if anyone else wants to take that part over - you're welcome.

**Comment by AhmedAlshair** [comment]
Has this issue been fixed or can be using a workaround? I'm still getting the same error.
