### ISSUE TITLE
google is not defined handleAutoComplete node_modules/react-google-autocomplete/lib/index.js:93

### ISSUE THREAD

**Issue by Sandeep200995** [ErrorPro/react-google-autocomplete#80]
![Screenshot 2020-07-01 at 1 46 02 PM](https://user-images.githubusercontent.com/41103211/86220433-36b23980-bba1-11ea-8428-7323b5125ecb.png)

**Comment by Granddevv** [comment]
same issue for me

**Comment by ErrorPro** [comment]
@Sandeep200995 just tested on my localhost - everything worked. Seems like you either forgot to add google script or [this part](https://github.com/ErrorPro/react-google-autocomplete/blob/master/src/index.js#L104) didn't work for you.

**Comment by bhimani07** [comment]
What was the workaround for you @Sandeep200995 ?

**Comment by emilguareno** [comment]
I had the same issue. Turned out to be an issue where if your parent component renders multiple times, then the loadScript for this plugin doesn't finish in time, and the second render checks if there is a script for it, which there is but it's not done loading yet. https://github.com/ErrorPro/react-google-autocomplete/blob/master/src/index.js#L109

**Comment by bhimani07** [comment]
How did you solve it? @emilguareno

**Comment by emilguareno** [comment]
I just made sure that the autocomplete component wasn't rendered multiple times. If you put a console.log you should only see one render.

**Comment by suskull** [comment]
You can try npm package call 'react-async-script-loader'.
use it as a HOC with your Component you use AutoComplete.
HOC will return you 2 props, isScriptLoaded, isScriptLoadSucceed, 
Check if isScriptLoaded, isScriptLoadSuccee is true then render <AutoComplete /> else render loading...
It worked for me.

**Comment by ErrorPro** [comment]
Hey! I just released a new version(v2) which should fix that issue. Also, make sure you pass the apiKey or have a google script in the document. Let me know if you still experience it. @Sandeep200995
