### ISSUE TITLE
Capture all results and not just the selected one

### ISSUE THREAD

**Issue by igorrmon** [ErrorPro/react-google-autocomplete#82]
Hi @ErrorPro.
Is it possible to somehow get all the Array of options that autocomplete presents or only the selected?

Congratulations on this project!!!

**Comment by ErrorPro** [comment]
Hi @igoRmon, thank you for your issue. This [line](https://github.com/ErrorPro/react-google-autocomplete/blob/master/src/index.js#L100) does the magic, it gets the current place and what that is depends on what you type in.

**Comment by ErrorPro** [comment]
Hi @igorrmon , I did some research regarding this issue and found the only way to get all list of results: read it from dom.
![image](https://user-images.githubusercontent.com/6295152/115118428-5cc78f80-9fa3-11eb-976d-9a9a92af7625.png)

Not sure how you can find that container though.
