### ISSUE TITLE
How to dynamic bounds

### ISSUE THREAD

**Issue by hungvtitdng** [ErrorPro/react-google-autocomplete#83]
hi @ErrorPro ,

I had built a website and used this package to project, In my project have a autocomplete but bounds dynamic by a select. 

This is my code
```php
<Autocomplete
    placeholder={placeholder}
    value={autoComplete.address ? autoComplete.address : ''}
    ...
    bounds={
        new window.google.maps.LatLngBounds(
            new window.google.maps.LatLng(
                parseFloat(location.lat_south_west),
                parseFloat(location.lng_south_west)
            ),
            new window.google.maps.LatLng(
                parseFloat(location.lat_north_east),
                parseFloat(location.lng_north_east)
            ),
        )
    }
    types={[]}
/>
```

the bounds just apply the first time, other times not working. It got old value from `location` from first time.
How to change bounds in the seconds, third time.

Thanks Bro,

**Comment by ErrorPro** [comment]
@hungvtitdng Hi, the library uses the bounds only on the first render(didMount), so what you would need to do is to re-render the whole Autocomplete when your props change, the easiest way to do so is `<Autocomplete key={Math.random()} />`
