### ISSUE TITLE
Options are not appearing 

### ISSUE THREAD

**Issue by leo-def** [ErrorPro/react-google-autocomplete#84]
I'm typing, but no suggestion is appearing and no error is catched.

![image](https://user-images.githubusercontent.com/7004464/93532408-5db61700-f917-11ea-8806-403af3cc040f.png)

Code: 
`   
 <Grid container spacing={2}>

      <Grid item sm={12}>

        <Autocomplete
          apiKey={googleApiKey}
          style={{ width: '90%' }}
          onPlaceSelected={(place: any) => {
            console.log('place', place)
          }}
          types={['(regions)', 'address', 'geocode']}
          componentRestrictions={{ country: 'br' }}
        />

      </Grid>

</Grid>

`

**Comment by coder36** [comment]
We're using ant design, and the options don't appear when inside a Model.

**Comment by ErrorPro** [comment]
@leo-def the component is basically just a regular `<input />`. The library does not modify or add the dom tree. Probably you need to pass additional styles for positioning and check the overflow/flow of your components.
