### ISSUE TITLE
How can I set output language? currently it's returning result in device language

### ISSUE THREAD

**Issue by Ogelet** [ErrorPro/react-google-autocomplete#85]

**Comment by igorrmon** [comment]
Hello, I have the same problem!

**Comment by igorrmon** [comment]
Hi @Ogelet , I have a solution to this problem, with output "formatted_address". You can use a request through geocode API where you can set the output language as a parameter.

[Geo code api](https://developers.google.com/maps/documentation/geocoding/start#:~:text=The%20Geocoding%20API%20is%20a,Client%20for%20Google%20Maps%20Services.)

**Comment by ErrorPro** [comment]
Also full list of [PlaceResult](https://developers.google.com/maps/documentation/javascript/reference/places-service#PlaceResult)
