### ISSUE TITLE
A string ref, "input", has been found within a strict mode tree

### ISSUE THREAD

**Issue by FlorianMrn** [ErrorPro/react-google-autocomplete#86]
Hi everyone,

First of all, thank you for your work.

I have this error since i installed this package : A string ref, "input", has been found within a strict mode tree.

I think this is from the index.js in lib folder file mainly because of this line : 

`return _react2.default.createElement('input', _extends({ ref: 'input' }, rest));}`

or this : 

`  _react2.default.cloneElement(this.props.input, _extends({}, this.props, {
          ref: 'input',
          onChange: function onChange(e) {
            _this7.onChange(e);
          }
        })),
        _react2.default.createElement('div', { ref: 'div' })`

I started code one year ago. Can i get help to change these lines ?

Thanks you !

**Comment by ErrorPro** [comment]
Hi @FlorianMrn, I just published v2 which has a `ref` prop support and more. Thanks for your issue!
