### ISSUE TITLE
How to access distance_meters from predictions objects

### ISSUE THREAD

**Issue by djwood** [ErrorPro/react-google-autocomplete#87]
How can I get the _distance_meters_ results in the predictions objects when an Autocomplete request is made with the { lat, lng } _origin_ option as specified in the Google API docs? If this isn't readily accessible, it would be a useful feature to return it with the OnPlaceSelected() results. Thanks!

**Comment by ErrorPro** [comment]
@djwood Hey! I've just added a new version and now it passes the autocomplete instance to the `onPlaceSelected` [method](https://github.com/ErrorPro/react-google-autocomplete#props). Please have a look and let me know if that works for you.
