### ISSUE TITLE
How to set default value in the autocomplete field

### ISSUE THREAD

**Issue by DebRoy15** [ErrorPro/react-google-autocomplete#88]
can you say which parameter I should use in your autocomplete component to set the default value in it?

**Comment by vallard** [comment]
came here to wish I had this ability as well since.

**Comment by vallard** [comment]
Ah... it was already mentioned in a closed issue #78 Probably need to put this in the docs: 

```
<Autocomplete
   ...
   defaultValue = "Los Angeles"
/>
```
