### ISSUE TITLE
You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors

### ISSUE THREAD

**Issue by benderlidze** [ErrorPro/react-google-autocomplete#89]
Hi, thanks for your component, it is great.
I have a leaflet map with `react-leaflet-google-layer` and it is using google API too. 
Got a problem with this `You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors`. 
I tried to add/remove <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key="> to different parts of the index.html, does not help. 
"react-google-autocomplete": "^1.2.6",
Is there any way to fix this? 
Thanks.

**Comment by claudiomnec** [comment]
I have the same problem when I use it in conjunction with the react-google-places-autocomplete library

**Comment by adrielgro** [comment]
I have the same problem when i use with react-google-autocomplete

**Comment by ErrorPro** [comment]
@adrielgro @claudiomnec @benderlidze Hi! I've just released a new version(v2) which should fix that issue. Please let me know if you still encounter it. Thanks!

**Comment by pekac** [comment]
Hey @ErrorPro! 

Got something related to this issue.

I am using:
- `google-map-react v2.1.9`
- `react-google-autocomplete v2.1.2`

The error I'm getting is:
`Google maps places API must be loaded`

Ofc, once the map is removed from the same page - the autocomplete works properly!
Also, the map component works both with the autocomplete and without it :)

**Comment by ErrorPro** [comment]
hey @pekac ! Thanks for your message. We tried to reproduce the issue but unfortunately, we could not. Could you add some more info or show/send the piece of code how you are using it?
https://monosnap.com/file/RDqGF7o5Dx4kyivGCykZNMAxJoBRow
https://monosnap.com/file/kskdTqChukqlS7Wbaccfcy1uL7bGdg

**Comment by pekac** [comment]
Hey @ErrorPro ! Thanks for looking into it so deeply!
> It seems like you have google but do not have google maps places
Definitely looks that way.

Give me some time to spin up a min-reproducible repo. I believe this will be the easiest way to pinpoint the issue.
Will share it with you afterwards :)

**Comment by thebiltheory** [comment]
✋🏽 Same here.

Using: 
- `"@react-google-maps/api": "^2.1.1",`
- `"react-google-autocomplete": "^2.1.2",`

```javascript
You have included the Google Maps JavaScript API multiple times on this page.
This may cause unexpected errors.


Uncaught (in promise) TypeError: Cannot read property 'um' of undefined
```

**Comment by ErrorPro** [comment]
@thebiltheory Hey, is it possible to share a piece of code(if it's the same component). I want to understand the flow, which lib first gets to load google API, thanks!

**Comment by ErrorPro** [comment]
I just found out the way to reproduce it. The problem is that autocomplete library needs `places` API to be loaded. The only way to load `places` API via [URL](https://developers.google.com/maps/documentation/javascript/libraries). So what happens is: somewhere in the code you already require google map API(any map library or directly) without `places` API in the URL so that this library sees google available but cannot get access to `google.maps.places`. The easiest way would be to paste the full URL with all libraries included in the HTML e.g. 
```
<script
  type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=apiKey&libraries=places,anyOtherLib"
></script>
```

**Comment by GarryOne** [comment]
If you're using this package alongside with `google-map-react`, you can just tell the last package to include the `places` api.
```
<GoogleMapReact
            bootstrapURLKeys={{
              key: API_KEY,
              libraries:['places'],
            }}
/>
            ```

**Comment by izzyworks89** [comment]
How? @GarryOne 
I am using both. 
 "@react-google-maps/api": "^2.1.1",
 "react-google-autocomplete": "^2.1.2",
How do i do that

**Comment by JAndresHJGlobant** [comment]
@izzyworks89 You could try by setting the API key and the places library by using the `useLoadScript` provided by @react-google-maps/api. I mean something like this:

`
const { isLoaded, loadError } = useLoadScript({
    googleMapsApiKey: API_KEY,
    libraries: ['places'],
  });
`

**Comment by im-tridevsharma** [comment]
Use this code 
`const { isLoaded, loadError } = useLoadScript({ googleMapsApiKey: API_KEY, libraries: ['places'], });`

And when rendering Autocomplete, Please enclose Autocomplete in 
`{isLoaded && <AutoComplete />}`

**Comment by bek-sidikovich02** [comment]
Hi guys!
I have been using react-google-autocomplete so far, but it can not show usa regions and cities also street number, pls
I need to have your favour

**Comment by mschipperheyn** [comment]
One thing to be aware of that even with useLoadScript, you have to make sure that both urls are identical, i.e. contain the same parameters in the same order. I recommend loading the script in a separate component

```
const MyPlacesComponentImpl = ({ googleMapsScriptBaseUrl }) => { 
    const {
        placesService,
        placePredictions,
        getPlacePredictions,
        isPlacePredictionsLoading,
    } = usePlacesService({
        googleMapsScriptBaseUrl,
    });
   [...] 
}

const libraries = ['places'];
const MyPlacesComponent = ({ googleMapsApiKey, language }) => {
    const { isLoaded, loadError, url } = useLoadScript({
        googleMapsApiKey,
        id: 'google-map',
        libraries,
        language,
    });

    if (!isLoaded) {
        return <Loading />;
    }
    if (loadError) {
        return <LoadingError />;
    }
    return (
        <MyPlacesComponentImpl googleMapsScriptBaseUrl={url} />
    );
}

export default MyPlacesComponent;
```

**Comment by popcorn245** [comment]
If using one of the loaders you will need to do a check to see if google maps is already loaded and then use the already existing instance, and you will also need to check to see if the loader exists so that you can wait for the scripts to finish loading before trying again. Here is my code, hope this helps someone who is as lost as I was lol. ^_^

```typescript
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  async loadGoogleMaps(options?: LoaderOptions) {
    if (window?.google) return window.google;
    if ((window as any)?._dk_google_maps_loader_cb) {
      await this.sleep(200);
      return this.loadGoogleMaps();
    }
    try {
      const loader = new Loader(this.googleMapsKey, {
        libraries: ["places"],
        ...options,
      });

      return loader.load();
    } catch (e) {
      console.log(e);
      setTimeout(this.loadGoogleMaps.bind(this), 2000);
    }
  }
```

NOTE: I am using google-maps package
https://github.com/davidkudera/google-maps-loader#readme

**Comment by vitorcosta039** [comment]
@thebiltheory did you manage to solve the problem? i have the same settings as you

**Comment by bek-sidikovich02** [comment]
Thanks,so much!
Marc

**Comment by raja-muhammad-asher** [comment]
I had the same problem because of using useLoadScript with and without places in two different components. In one component, places were not required but in the other I needed 'places'. I made the call to useLoadScript by including 'places' in both components and that removed this problem.
```
const {isLoaded} = useLoadScript({ googleMapsApiKey: YOUR_API_KEY, libraries: ['places'], })
```

**Comment by AlainYRS** [comment]
I have the same problem but:
-I am working in two independent components to be used on demand when they were required at any moment in any project so they can't share a url or anything.
-What could I do when both components are needed in the same project since they suppose to be provided with props/parameters (ApiKey) without any code modification?

**Comment by raja-muhammad-asher** [comment]
> I have the same problem but: -I am working in two independent components to be used on demand when they were required at any moment in any project so they can't share a url or anything. -What could I do when both components are needed in the same project since they suppose to be provided with props/parameters (ApiKey) without any code modification?

Please use 
const {isLoaded} = useLoadScript({ googleMapsApiKey: YOUR_API_KEY, })

in both components. It should resolve your problem

**Comment by AlainYRS** [comment]
> > I have the same problem but: -I am working in two independent components to be used on demand when they were required at any moment in any project so they can't share a url or anything. -What could I do when both components are needed in the same project since they suppose to be provided with props/parameters (ApiKey) without any code modification?
> 
> Please use const {isLoaded} = useLoadScript({ googleMapsApiKey: YOUR_API_KEY, })
> 
> in both components. It should resolve your problem

Thanks, it can fix my multiple Api calls but unfortunately there is a new error "ReferenceError: google is not defined" since I use GoogleMap too.

Do you have an idea of how could it be fixed?

**Comment by hayatkhan1196** [comment]
it working for me 
const {isLoaded} = useLoadScript({ googleMapsApiKey: YOUR_API_KEY, libraries: ['places'], })

**Comment by ewarrenG** [comment]
Has anyone experienced this across two separate components? In one I use autocomplete, in another I use maps. In the autocomplete example, I follow the [example](https://mui.com/material-ui/react-autocomplete/#google-maps-place) material ui provides. In the maps example, I follow the [example](https://visgl.github.io/react-google-maps/docs/api-reference/components/api-provider) react google maps provides. 

Has anyone come up with a solution to load the Google Maps API once for these two different usecases?

Thanks in advance!

**Comment by CamiloTass** [comment]
Hi, I see that there are many examples but I keep getting the same problem. When I load the google-places-autocomplete component I keep getting the problem that: You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors. And when both things get blocked, the Google map stops searching for places. Here I leave the code to know if I am doing something wrong or if someone found the solution and can help me.



```
<div className='w-[40%]'>
<APIProvider apiKey={API_KEY_GOOGLE_MAPS}>
					<MapGoogle
						customControlPermission
						MapHandlerPermission
						UndoRedoControlPermission
						dispatch={dispatch}
						state={state}
						selectedPlace={selectedPlace}
					/>
				</APIProvider>
								<span>lugar de inicio</span>
								<GooglePlacesAutocomplete
									apiKey={API_KEY_GOOGLE_MAPS}
									autocompletionRequest={{
										bounds: [{ lat: 50, lng: 50 }]
									}}
									onLoadFailed={(error) =>
										console.error('Could not inject Google script --------------', error)
									}
									selectProps={{
										value,
										onChange: setValue
									}}
								/>
							</div>
```

**Comment by gorillah** [comment]
`"use client";

import { LoadScript, Libraries } from "@react-google-maps/api";
import React, { useState, useEffect } from "react";

const GOOGLE_LIBRARIES: Libraries = ["places", "marker"];

const LoadGoogleProvider = ({ children }: { children: React.ReactNode }) => {
  const [isLoaded, setIsLoaded] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!process.env.NEXT_PUBLIC_GOOGLE_API_KEY) {
      setError("Google Maps API key is missing.");
    }
  }, []);

  const onLoad = () => setIsLoaded(true);
  const onError = () => setError("Failed to load Google Maps");

  return process.env.NEXT_PUBLIC_GOOGLE_API_KEY ? (
    <LoadScript
      googleMapsApiKey={process.env.NEXT_PUBLIC_GOOGLE_API_KEY}
      libraries={GOOGLE_LIBRARIES}
      onLoad={onLoad}
      onError={onError}
    >
      {isLoaded ? children : <p>Loading Google Maps...</p>}
      {error && <p>{error}</p>}
    </LoadScript>
  ) : (
    <p>{error}</p>
  );
};

export default LoadGoogleProvider;
`

this worked for me, make sure to wrap in layout where its used

**Comment by gorillah** [comment]
```
"use client";

import { LoadScript, Libraries } from "@react-google-maps/api";
import React, { useState, useEffect } from "react";

const GOOGLE_LIBRARIES: Libraries = ["places", "marker"];

const LoadGoogleProvider = ({ children }: { children: React.ReactNode }) => {
const [isLoaded, setIsLoaded] = useState(false);
const [error, setError] = useState<string | null>(null);

useEffect(() => {
if (!process.env.NEXT_PUBLIC_GOOGLE_API_KEY) {
setError("Google Maps API key is missing.");
}
}, []);

const onLoad = () => setIsLoaded(true);
const onError = () => setError("Failed to load Google Maps");

return process.env.NEXT_PUBLIC_GOOGLE_API_KEY ? (

{isLoaded ? children :

Loading Google Maps...

}
{error &&
{error}

}

) : (
{error}


);
};
export default LoadGoogleProvider;
````

this worked for me, make sure to wrap in layout where its used

**Comment by penderuk** [comment]
> I just found out the way to reproduce it. The problem is that autocomplete library needs `places` API to be loaded. The only way to load `places` API via [URL](https://developers.google.com/maps/documentation/javascript/libraries). So what happens is: somewhere in the code you already require google map API(any map library or directly) without `places` API in the URL so that this library sees google available but cannot get access to `google.maps.places`. The easiest way would be to paste the full URL with all libraries included in the HTML e.g.
> 
> ```
> <script
>   type="text/javascript"
>   src="https://maps.googleapis.com/maps/api/js?key=apiKey&libraries=places,anyOtherLib"
> ></script>
> ```

Thanks, @ErrorPro! This worked for me. I'm using `react-google-autocomplete` and `@vis.gl/react-google-maps` on the same page. I included the script in the `<Head />` of my Next.js page, and now other libraries that use the Google Maps API no longer try to inject the maps initialization script into the page.
