### ISSUE TITLE
componentRestrictions

### ISSUE THREAD

**Issue by AlmogRnD** [ErrorPro/react-google-autocomplete#9]
Is it possible to set componentRestrictions for example I only want to show a specific country.

**Comment by AlmogRnD** [comment]
Basically are you supporting the following 

components — A grouping of places to which you would like to restrict your results. Currently, you can use components to filter by country. The country must be passed as a two character, ISO 3166-1 Alpha-2 compatible country code. For example: components=country:fr would restrict your results to places within France.

**Comment by ErrorPro** [comment]
@AlmogRnD Hi, thank you for your issue. I've made some changes regarding your issue. Please check @1.0.9 version and README.md as well.

**Comment by AlmogRnD** [comment]
thanks

**Comment by AlmogRnD** [comment]
I just tested and it's not working, did the update this is the my code 

```
<Geosuggest
                            onFocus={this.onFocus}
                            onBlur={this.onBlur}
                            onChange={this.onChangeLocation}
                            onSuggestSelect={this.onSuggestSelect}
                            onSuggestNoResults={this.onSuggestNoResults}
                            componentRestrictions={{country: "us"}}
                            location={new google.maps.LatLng(37.09024, -95.712891)}
                            radius="20"  />
```

**Comment by ErrorPro** [comment]
@AlmogRnD This is the working code i tested out yesterday: 

```
<Autocomplete
    style={{width: '90%'}}
    onPlaceSelected={(place) => {
      console.log(place);
    }}
    types={['(regions)']}
    componentRestrictions={{country: "ru"}}
/>```

Did you update the library? The current version is 1.0.9. Also i will provide you the working example(jsbin) later.

**Comment by AlmogRnD** [comment]
When I test your code out I get the following error 
Uncaught Error: Missing parameter. You must specify location.

You have to set 
 `location={new google.maps.LatLng(37.09024, -95.712891)}
`
I tested the following out and If I do a search for "sp" spain still shows up 

```
<Geosuggest
                            onFocus={this.onFocus}
                            onBlur={this.onBlur}
                            onChange={this.onChangeLocation}
                            onSuggestSelect={this.onSuggestSelect}
                            onSuggestNoResults={this.onSuggestNoResults}
                            types={['(regions)']}
                            componentRestrictions={{country: "us"}}
                            location={new google.maps.LatLng(37.09024, -95.712891)}
                            radius="20"  />
```

**Comment by ErrorPro** [comment]
@AlmogRnD Hey, sorry for delay. Check this out pls http://jsbin.com/dowinuzuvi/edit?js,output also i updated the doc. Now you can pass `bounds` prop to google autocomplete.

**Comment by ErrorPro** [comment]
i'm closing this issue.
