### ISSUE TITLE
How to retrieve the first prediction from the list after pressing Enter?

### ISSUE THREAD

**Issue by abdo17rabah** [ErrorPro/react-google-autocomplete#92]
How can i select the first prediction of the list after hitting the 'Enter button' ?
`<Autocomplete
            placeholder="Where ?"
            className={'${styles.unstyled} border-0 mr-3 w-100'}
            onPlaceSelected={(place) => {
              setLocation({ lat: place.geometry.location.lat(), lng: place.geometry.location.lng() });
              onSubmit({ lat: place.geometry.location.lat(), lng: place.geometry.location.lng() });
            }}
            types={['address']}
            componentRestrictions={{ country: 'fr' }}
          />`

**Comment by ErrorPro** [comment]
@abdo17rabah Hi, there's no way to get a list of predictions from the autocomplete [itself](https://developers.google.com/maps/documentation/javascript/reference/places-widget#Autocomplete.getPlace).
