### ISSUE TITLE
How to use with TypeScript?

### ISSUE THREAD

**Issue by athenawisdoms** [ErrorPro/react-google-autocomplete#93]
Tried installing the type definitions using

    yarn add --dev @types/react-google-autocomplete

but encountered the error

> error An unexpected error occurred: "https://registry.yarnpkg.com/@types%2freact-google-autocomplete: Not found".

Whats the correct way to install the TypeScript type definitions? Thanks!

**Comment by ErrorPro** [comment]
@athenawisdoms Hi, I just published 1.3.0 with TS annotations. Please refer to `README.md` to see how to use it.
